import { mkdir, readdir, writeFile } from 'node:fs/promises';
import { relative, resolve } from 'node:path';
import { identifierSchema } from '@graph-native/contracts';

export interface ScaffoldResult {
  readonly id: string;
  readonly directory: string;
  readonly files: readonly string[];
}

function titleFromId(id: string): string {
  return id
    .split(/[._-]/)
    .filter(Boolean)
    .map((part) => `${part[0]?.toUpperCase()}${part.slice(1)}`)
    .join(' ');
}

function sourceTemplate(id: string, title: string): string {
  return [
    "import { defineHandlers, definePack } from '@graph-native/pack-sdk';",
    '',
    'export const pack = definePack({',
    `  id: '${id}',`,
    "  version: '0.1.0',",
    `  name: '${title} Pack',`,
    "  description: 'A minimal Industry Pack generated by Graph Native Workbench.',",
    "  license: 'MIT',",
    '  ontology: {',
    '    objectTypes: [{',
    "      id: 'artifact',",
    "      label: 'Artifact',",
    "      description: 'A reusable output produced by this Pack.',",
    '      fields: {',
    "        content: { type: 'string', required: true, description: 'Artifact content.' },",
    '      },',
    '    }],',
    '    relationTypes: [],',
    '  },',
    '  roles: [],',
    '  tools: [],',
    '  evaluations: [],',
    '  deliverables: [{',
    "    id: 'result', label: 'Result', description: 'The first Pack result.',",
    `    graphId: '${id}.workflow', stateField: 'result', mediaType: 'text/plain',`,
    '  }],',
    '  fixtures: [{',
    "    id: 'smoke', label: 'Smoke fixture', description: 'Proves the generated Pack can run.',",
    `    graphId: '${id}.workflow', input: { topic: 'hello' }, decisions: {},`,
    "    expectations: [{ field: 'result', operator: 'includes', value: 'hello', description: 'Produces a visible result.' }],",
    '  }],',
    '  graphs: [{',
    `    id: '${id}.workflow',`,
    '    version: 1,',
    `    name: '${title} workflow',`,
    "    description: 'Turn a topic into a visible first result.',",
    '    state: { fields: {',
    "      topic: { type: 'string', required: true, description: 'Input topic.' },",
    "      result: { type: 'string', required: false, description: 'Generated result.' },",
    '    } },',
    '    nodes: [',
    "      { id: 'start', kind: 'trigger', label: 'Start', description: 'Accept input.', reads: ['topic'], writes: [], config: {} },",
    `      { id: 'produce', kind: 'function', label: 'Produce', description: 'Create the result.', handler: '${id}.produce', reads: ['topic'], writes: ['result'], config: {} },`,
    '    ],',
    "    edges: [{ id: 'e_start_produce', source: 'start', target: 'produce', on: 'success' }],",
    '    budget: { maxSteps: 8, maxDurationMs: 30_000, maxConcurrency: 2 },',
    '  }],',
    '});',
    '',
    'export const handlers = defineHandlers({',
    `  '${id}.produce': ({ state }) => ({ result: 'Pack ${id} processed: ' + String(state.topic) }),`,
    '});',
    '',
    'export async function projector(store, run) {',
    '  const recordedAt = new Date().toISOString();',
    '  await store.appendObject({',
    "    id: run.runId + '.artifact', type: 'artifact', version: 1, status: 'confirmed',",
    "    data: { content: String(run.state.result ?? '') }, validFrom: recordedAt, validTo: null,",
    `    provenance: { sourceIds: [], producedByRunId: run.runId, producedByNodeId: 'produce', actorId: '${id}.runtime', recordedAt },`,
    '  });',
    '}',
    '',
  ].join('\n');
}

export async function scaffoldPack(idInput: string, targetDirectory: string): Promise<ScaffoldResult> {
  const id = identifierSchema.parse(idInput);
  const directory = resolve(targetDirectory);
  await mkdir(directory, { recursive: true });
  if ((await readdir(directory)).length > 0) {
    throw new Error(`Target directory "${directory}" is not empty.`);
  }

  const title = titleFromId(id);
  const repositoryPath = relative(process.cwd(), directory).replaceAll('\\', '/');
  const packageJson = `${JSON.stringify(
    {
      name: `@graph-native/pack-${id}`,
      version: '0.1.0',
      private: false,
      type: 'module',
      license: 'MIT',
      exports: './src/index.ts',
      dependencies: {
        '@graph-native/core': 'workspace:*',
        '@graph-native/pack-sdk': 'workspace:*',
      },
    },
    null,
    2,
  )}\n`;
  const readme = [
    `# ${title} Pack`,
    '',
    'Generated Industry Pack for Graph Native Workbench.',
    '',
    'From the repository root:',
    '',
    '```bash',
    `pnpm graphwork pack validate ${repositoryPath}/src/index.ts`,
    `pnpm graphwork pack test ${repositoryPath}/src/index.ts`,
    `pnpm graphwork pack build ${repositoryPath}/src/index.ts --output ${id}-0.1.0.gpack`,
    '```',
    '',
  ].join('\n');

  await mkdir(resolve(directory, 'src'));
  const files = ['package.json', 'README.md', 'src/index.ts'];
  await Promise.all([
    writeFile(resolve(directory, 'package.json'), packageJson, 'utf8'),
    writeFile(resolve(directory, 'README.md'), readme, 'utf8'),
    writeFile(resolve(directory, 'src/index.ts'), sourceTemplate(id, title), 'utf8'),
  ]);
  return { id, directory, files };
}
