import { mkdir, readdir, writeFile } from 'node:fs/promises';
import { relative, resolve } from 'node:path';
import { identifierSchema } from '@graph-workbench/contracts';

export interface ScaffoldResult {
  readonly id: string;
  readonly directory: string;
  readonly files: readonly string[];
}

export interface ScaffoldOptions {
  readonly standalone?: boolean;
}

function titleFromId(id: string): string {
  return id
    .split(/[._-]/)
    .filter(Boolean)
    .map((part) => `${part[0]?.toUpperCase()}${part.slice(1)}`)
    .join(' ');
}

function sourceTemplate(id: string, title: string, standalone = false): string {
  return [
    ...(standalone ? [] : ["import { defineHandlers, definePack } from '@graph-workbench/pack-sdk';", '']),
    standalone ? 'export const pack = {' : 'export const pack = definePack({',
    `  id: '${id}',`,
    "  version: '0.1.0',",
    `  name: '${title} Pack',`,
    "  description: 'A minimal Industry Pack generated by Graph Workbench.',",
    "  license: 'MIT',",
    '  ontology: {',
    '    objectTypes: [{',
    "      id: 'artifact',",
    "      label: 'Artifact',",
    "      description: 'A reusable output produced by this Pack.',",
    '      fields: {',
    "        content: { type: 'string', required: true, description: 'Artifact content.' },",
    '      },',
    '    }],',
    '    relationTypes: [],',
    '  },',
    '  roles: [],',
    '  tools: [],',
    '  evaluations: [],',
    '  deliverables: [{',
    "    id: 'result', label: 'Result', description: 'The first Pack result.',",
    `    graphId: '${id}.workflow', stateField: 'result', mediaType: 'text/plain',`,
    '  }],',
    '  fixtures: [{',
    "    id: 'smoke', label: 'Smoke fixture', description: 'Proves the generated Pack can run.',",
    `    graphId: '${id}.workflow', input: { topic: 'hello' }, decisions: {},`,
    "    expectations: [{ field: 'result', operator: 'includes', value: 'hello', description: 'Produces a visible result.' }],",
    '  }],',
    '  graphs: [{',
    `    id: '${id}.workflow',`,
    '    version: 1,',
    `    name: '${title} workflow',`,
    "    description: 'Turn a topic into a visible first result.',",
    '    state: { fields: {',
    "      topic: { type: 'string', required: true, description: 'Input topic.' },",
    "      result: { type: 'string', required: false, description: 'Generated result.' },",
    '    } },',
    '    nodes: [',
    "      { id: 'start', kind: 'trigger', label: 'Start', description: 'Accept input.', reads: ['topic'], writes: [], config: {} },",
    `      { id: 'produce', kind: 'function', label: 'Produce', description: 'Create the result.', handler: '${id}.produce', reads: ['topic'], writes: ['result'], config: {} },`,
    '    ],',
    "    edges: [{ id: 'e_start_produce', source: 'start', target: 'produce', on: 'success' }],",
    '    budget: { maxSteps: 8, maxDurationMs: 30_000, maxConcurrency: 2 },',
    '  }],',
    standalone ? '};' : '});',
    '',
    standalone ? 'export const handlers = {' : 'export const handlers = defineHandlers({',
    `  '${id}.produce': ({ state }) => ({ result: 'Pack ${id} processed: ' + String(state.topic) }),`,
    standalone ? '};' : '});',
    '',
    'export async function projector(store, run) {',
    '  const recordedAt = new Date().toISOString();',
    '  await store.appendObject({',
    "    id: run.runId + '.artifact', type: 'artifact', version: 1, status: 'confirmed',",
    "    data: { content: String(run.state.result ?? '') }, validFrom: recordedAt, validTo: null,",
    `    provenance: { sourceIds: [], producedByRunId: run.runId, producedByNodeId: 'produce', actorId: '${id}.runtime', recordedAt },`,
    '  });',
    '}',
    '',
  ].join('\n');
}

export async function scaffoldPack(
  idInput: string,
  targetDirectory: string,
  options: ScaffoldOptions = {},
): Promise<ScaffoldResult> {
  const id = identifierSchema.parse(idInput);
  const directory = resolve(targetDirectory);
  await mkdir(directory, { recursive: true });
  if ((await readdir(directory)).length > 0) {
    throw new Error(`Target directory "${directory}" is not empty.`);
  }

  const title = titleFromId(id);
  const sourceExtension = options.standalone ? 'mjs' : 'ts';
  const sourcePath = `src/index.${sourceExtension}`;
  const repositoryPath = relative(process.cwd(), directory).replaceAll('\\', '/');
  const modulePath = `${repositoryPath}/${sourcePath}`;
  const runner = options.standalone ? 'npx graph-workbench' : 'pnpm graph-workbench';
  const packageJson = `${JSON.stringify(
    {
      name: `@graph-workbench/pack-${id}`,
      version: '0.1.0',
      private: false,
      type: 'module',
      license: 'MIT',
      exports: `./${sourcePath}`,
      ...(options.standalone ? {} : {
        dependencies: {
          '@graph-workbench/core': 'workspace:*',
          '@graph-workbench/pack-sdk': 'workspace:*',
        },
      }),
    },
    null,
    2,
  )}\n`;
  const readme = [
    `# ${title} Pack`,
    '',
    'Generated Industry Pack for Graph Workbench.',
    '',
    options.standalone
      ? 'From the directory where you created this Pack:'
      : 'From the repository root:',
    '',
    '```bash',
    `${runner} pack validate "${modulePath}"`,
    `${runner} pack test "${modulePath}"`,
    `${runner} pack run "${modulePath}" --set topic=hello`,
    `${runner} pack build "${modulePath}" --output ${id}-0.1.0.gpack`,
    '```',
    '',
  ].join('\n');

  await mkdir(resolve(directory, 'src'));
  const files = ['package.json', 'README.md', sourcePath];
  await Promise.all([
    writeFile(resolve(directory, 'package.json'), packageJson, 'utf8'),
    writeFile(resolve(directory, 'README.md'), readme, 'utf8'),
    writeFile(resolve(directory, sourcePath), sourceTemplate(id, title, options.standalone), 'utf8'),
  ]);
  return { id, directory, files };
}
