import type { GraphDefinition, IndustryPackManifest } from '@graph-workbench/contracts';

const budget = { maxSteps: 80, maxDurationMs: 60_000, maxConcurrency: 8 };

const strategyGraph: GraphDefinition = {
  id: 'quantitative_finance.strategy_governance',
  version: 1,
  name: 'Research-to-execution governance',
  description: 'Turns a mandate and hypothesis into independently approved order intent and an attributable OMS request.',
  state: { fields: {
    strategy_id: { type: 'string', required: true, description: 'Stable strategy identifier.' },
    account_id: { type: 'string', required: true, description: 'Execution account boundary.' },
    objective: { type: 'string', required: true, description: 'Research and portfolio objective.' },
    universe: { type: 'array', required: true, description: 'Point-in-time investable universe.' },
    benchmark: { type: 'string', required: true, description: 'Mandate benchmark.' },
    capital_usd: { type: 'number', required: true, description: 'Capital used for reference sizing.' },
    constraints: { type: 'object', required: true, description: 'Risk and mandate constraints.' },
    as_of: { type: 'string', required: true, description: 'Point-in-time research date.' },
    mandate: { type: 'object', required: false, description: 'Normalized mandate.' },
    hypothesis: { type: 'object', required: false, description: 'Falsifiable strategy hypothesis.' },
    backtest_requests: { type: 'array', required: false, description: 'Per-instrument simulation requests.' },
    backtest_results: { type: 'array', required: false, description: 'Point-in-time simulation evidence.' },
    research_summary: { type: 'object', required: false, description: 'Aggregated research evidence.' },
    target_portfolio: { type: 'array', required: false, description: 'Proposed target weights.' },
    risk_assessment: { type: 'object', required: false, description: 'Independent limit and stress assessment.' },
    risk_approved: { type: 'boolean', required: false, description: 'Independent risk decision.' },
    compliance_approved: { type: 'boolean', required: false, description: 'Compliance decision.' },
    execution_approved: { type: 'boolean', required: false, description: 'Execution authorization.' },
    order_intent: { type: 'object', required: false, description: 'Approved but not yet executed orders.' },
    execution_request: { type: 'object', required: false, description: 'OMS submission receipt.' },
    strategy_execution_record: { type: 'string', required: false, description: 'Governed release record.' },
    rejection_reason: { type: 'string', required: false, description: 'Stopped-work explanation.' },
  } },
  nodes: [
    { id: 'start', kind: 'trigger', label: 'Strategy mandate', description: 'Accept mandate, universe, constraints and point-in-time date.', reads: ['strategy_id', 'account_id', 'objective', 'universe', 'benchmark', 'capital_usd', 'constraints', 'as_of'], writes: [], config: {} },
    { id: 'normalize_mandate', kind: 'function', label: 'Normalize mandate', description: 'Create a stable research and account boundary.', handler: 'quantitative_finance.normalize_mandate', reads: ['strategy_id', 'objective', 'universe', 'benchmark', 'capital_usd', 'constraints', 'as_of'], writes: ['mandate'], config: { roleId: 'portfolio_manager' } },
    { id: 'formulate_hypothesis', kind: 'agent', label: 'Formulate hypothesis', description: 'Create a falsifiable point-in-time signal hypothesis.', handler: 'quantitative_finance.formulate_hypothesis', reads: ['objective', 'benchmark', 'mandate'], writes: ['hypothesis'], config: { roleId: 'quant_researcher', toolIds: ['market_data_read'] } },
    { id: 'prepare_backtests', kind: 'function', label: 'Prepare simulations', description: 'Fan research out across the declared universe.', handler: 'quantitative_finance.prepare_backtests', reads: ['strategy_id', 'universe', 'benchmark', 'as_of'], writes: ['backtest_requests'], config: {} },
    { id: 'run_backtests', kind: 'map', label: 'Run point-in-time backtests', description: 'Evaluate instruments concurrently through a specialist simulation boundary.', reads: ['backtest_requests'], writes: ['backtest_results'], config: { graphId: 'quantitative_finance.backtest_instrument', itemsField: 'backtest_requests', itemField: 'request', resultField: 'result', outputField: 'backtest_results', inputMapping: {}, maxItems: 500, maxConcurrency: 12 } },
    { id: 'aggregate_research', kind: 'function', label: 'Aggregate evidence', description: 'Require complete out-of-sample evidence before portfolio construction.', handler: 'quantitative_finance.aggregate_research', reads: ['backtest_results'], writes: ['research_summary'], config: { evaluationId: 'research_validity' } },
    { id: 'construct_portfolio', kind: 'agent', label: 'Construct portfolio', description: 'Convert evidence into constrained target weights.', handler: 'quantitative_finance.construct_portfolio', reads: ['mandate', 'hypothesis', 'backtest_results', 'research_summary'], writes: ['target_portfolio'], config: { roleId: 'portfolio_manager' } },
    { id: 'assess_risk', kind: 'function', label: 'Calculate independent risk', description: 'Check drawdown, exposure, stress loss and model-risk limits.', handler: 'quantitative_finance.assess_risk', reads: ['constraints', 'research_summary', 'target_portfolio', 'capital_usd'], writes: ['risk_assessment'], config: { roleId: 'risk_manager', toolIds: ['risk_engine_read'], evaluationId: 'risk_limits' } },
    { id: 'risk_approval', kind: 'human', label: 'Independent risk approval', description: 'Pause for accountable risk acceptance.', reads: ['mandate', 'research_summary', 'target_portfolio', 'risk_assessment'], writes: ['risk_approved'], config: { decisionField: 'risk_approved', roleId: 'risk_manager', evaluationId: 'risk_approval' } },
    { id: 'risk_route', kind: 'router', label: 'Route risk decision', description: 'Stop rejected strategies before compliance or execution.', reads: ['risk_approved'], writes: [], config: {} },
    { id: 'compliance_approval', kind: 'human', label: 'Compliance approval', description: 'Approve mandate, restrictions and intended execution.', reads: ['mandate', 'hypothesis', 'target_portfolio', 'risk_assessment'], writes: ['compliance_approved'], config: { decisionField: 'compliance_approved', roleId: 'compliance_officer', evaluationId: 'compliance_approval' } },
    { id: 'compliance_route', kind: 'router', label: 'Route compliance', description: 'Separate authorized work from policy rejection.', reads: ['compliance_approved'], writes: [], config: {} },
    { id: 'prepare_order_intent', kind: 'function', label: 'Prepare order intent', description: 'Create sized order intent without routing an order.', handler: 'quantitative_finance.prepare_order_intent', reads: ['strategy_id', 'account_id', 'as_of', 'capital_usd', 'target_portfolio'], writes: ['order_intent'], config: { roleId: 'execution_trader' } },
    { id: 'execution_approval', kind: 'human', label: 'Authorize execution', description: 'Approve the final account-scoped order intent.', reads: ['order_intent', 'risk_assessment'], writes: ['execution_approved'], config: { decisionField: 'execution_approved', roleId: 'execution_trader', evaluationId: 'execution_authorization' } },
    { id: 'execution_route', kind: 'router', label: 'Route authorization', description: 'Submit only explicitly authorized orders.', reads: ['execution_approved'], writes: [], config: {} },
    { id: 'submit_orders', kind: 'function', label: 'Submit to OMS', description: 'Send the approved intent through the replaceable OMS adapter boundary.', handler: 'quantitative_finance.submit_orders', reads: ['account_id', 'order_intent'], writes: ['execution_request'], config: { roleId: 'execution_trader', toolIds: ['order_submit'] } },
    { id: 'publish_strategy', kind: 'function', label: 'Publish governance record', description: 'Preserve evidence, decisions and external execution receipt.', handler: 'quantitative_finance.publish_strategy', reads: ['strategy_id', 'objective', 'benchmark', 'as_of', 'research_summary', 'risk_assessment', 'risk_approved', 'compliance_approved', 'execution_approved', 'execution_request'], writes: ['strategy_execution_record'], config: {} },
    { id: 'record_rejection', kind: 'function', label: 'Record stopped work', description: 'Preserve the accountable rejection path.', handler: 'quantitative_finance.record_rejection', reads: ['risk_approved', 'compliance_approved', 'execution_approved'], writes: ['rejection_reason'], config: {} },
  ],
  edges: [
    { id: 'start.normalize', source: 'start', target: 'normalize_mandate', on: 'success' },
    { id: 'normalize.hypothesis', source: 'normalize_mandate', target: 'formulate_hypothesis', on: 'success' },
    { id: 'hypothesis.prepare', source: 'formulate_hypothesis', target: 'prepare_backtests', on: 'success' },
    { id: 'prepare.run', source: 'prepare_backtests', target: 'run_backtests', on: 'success' },
    { id: 'run.aggregate', source: 'run_backtests', target: 'aggregate_research', on: 'success' },
    { id: 'aggregate.portfolio', source: 'aggregate_research', target: 'construct_portfolio', on: 'success' },
    { id: 'portfolio.risk', source: 'construct_portfolio', target: 'assess_risk', on: 'success' },
    { id: 'risk.approval', source: 'assess_risk', target: 'risk_approval', on: 'success' },
    { id: 'risk.route', source: 'risk_approval', target: 'risk_route', on: 'success' },
    { id: 'risk.compliance', source: 'risk_route', target: 'compliance_approval', on: 'success', condition: { field: 'risk_approved', operator: 'equals', value: true } },
    { id: 'risk.reject', source: 'risk_route', target: 'record_rejection', on: 'success', condition: { field: 'risk_approved', operator: 'equals', value: false } },
    { id: 'compliance.route', source: 'compliance_approval', target: 'compliance_route', on: 'success' },
    { id: 'compliance.orders', source: 'compliance_route', target: 'prepare_order_intent', on: 'success', condition: { field: 'compliance_approved', operator: 'equals', value: true } },
    { id: 'compliance.reject', source: 'compliance_route', target: 'record_rejection', on: 'success', condition: { field: 'compliance_approved', operator: 'equals', value: false } },
    { id: 'orders.approval', source: 'prepare_order_intent', target: 'execution_approval', on: 'success' },
    { id: 'execution.route', source: 'execution_approval', target: 'execution_route', on: 'success' },
    { id: 'execution.submit', source: 'execution_route', target: 'submit_orders', on: 'success', condition: { field: 'execution_approved', operator: 'equals', value: true } },
    { id: 'execution.reject', source: 'execution_route', target: 'record_rejection', on: 'success', condition: { field: 'execution_approved', operator: 'equals', value: false } },
    { id: 'submit.publish', source: 'submit_orders', target: 'publish_strategy', on: 'success' },
  ],
  budget,
};

const backtestGraph: GraphDefinition = {
  id: 'quantitative_finance.backtest_instrument', version: 1, name: 'Instrument simulation',
  description: 'Reference adapter boundary for one point-in-time instrument backtest.',
  state: { fields: {
    request: { type: 'object', required: true, description: 'Simulation request.' },
    result: { type: 'object', required: false, description: 'Simulation evidence.' },
  } },
  nodes: [
    { id: 'start', kind: 'trigger', label: 'Simulation request', description: 'Accept one instrument request.', reads: ['request'], writes: [], config: {} },
    { id: 'run', kind: 'function', label: 'Run specialist backtest', description: 'Return deterministic zero-key reference evidence.', handler: 'quantitative_finance.run_backtest', reads: ['request'], writes: ['result'], config: { roleId: 'quant_researcher', toolIds: ['backtest_execute'] } },
  ],
  edges: [{ id: 'start.run', source: 'start', target: 'run', on: 'success' }], budget,
};

const reconciliationGraph: GraphDefinition = {
  id: 'quantitative_finance.execution_reconciliation', version: 1, name: 'Fill reconciliation and exception handling',
  description: 'Correlates external fills, reconciles books and safely cancels residual orders on mismatch.',
  trigger: { type: 'event', eventType: 'execution.fills_received', correlationField: 'execution_id' },
  state: { fields: {
    execution_id: { type: 'string', required: true, description: 'OMS execution identifier.' },
    strategy_id: { type: 'string', required: true, description: 'Strategy identifier.' },
    account_id: { type: 'string', required: true, description: 'Execution account.' },
    fills: { type: 'array', required: true, description: 'Observed fills.' },
    expected_notional_usd: { type: 'number', required: true, description: 'Expected signed notional.' },
    observed_at: { type: 'string', required: true, description: 'Observation timestamp.' },
    execution_observation: { type: 'object', required: false, description: 'Normalized fill observation.' },
    reconciliation_matched: { type: 'boolean', required: false, description: 'Reconciliation outcome.' },
    reconciliation: { type: 'object', required: false, description: 'Reconciliation evidence.' },
    residual_cancelled: { type: 'boolean', required: false, description: 'Residual cancellation status.' },
    cancellation_reference: { type: 'string', required: false, description: 'Cancellation evidence.' },
    reconciliation_record: { type: 'string', required: false, description: 'Books-and-records handoff.' },
  } },
  nodes: [
    { id: 'start', kind: 'trigger', label: 'Fill event', description: 'Accept correlated external fill evidence.', reads: ['execution_id', 'strategy_id', 'account_id', 'fills', 'expected_notional_usd', 'observed_at'], writes: [], config: {} },
    { id: 'normalize_execution', kind: 'function', label: 'Normalize fills', description: 'Create an attributable observation boundary.', handler: 'quantitative_finance.normalize_execution', reads: ['execution_id', 'strategy_id', 'account_id', 'fills', 'expected_notional_usd', 'observed_at'], writes: ['execution_observation'], config: { roleId: 'operations_analyst', toolIds: ['fill_read'] } },
    { id: 'reconcile', kind: 'function', label: 'Reconcile execution', description: 'Compare fills with expected order intent and tolerances.', handler: 'quantitative_finance.reconcile_execution', reads: ['fills', 'expected_notional_usd'], writes: ['reconciliation_matched', 'reconciliation'], config: { roleId: 'operations_analyst', evaluationId: 'reconciliation_integrity' } },
    { id: 'route_reconciliation', kind: 'router', label: 'Route reconciliation', description: 'Separate matched books from operational exceptions.', reads: ['reconciliation_matched'], writes: [], config: {} },
    { id: 'escalate_exception', kind: 'escalation', label: 'Escalate mismatch', description: 'Raise an accountable trading-operations exception.', reads: ['execution_id', 'reconciliation'], writes: [], config: { reason: 'Execution fills do not match approved intent; residual exposure requires action.', severity: 'critical', roleId: 'operations_analyst' } },
    { id: 'cancel_residual', kind: 'compensation', label: 'Cancel residual orders', description: 'Cancel open residuals without rewriting recorded fills.', handler: 'quantitative_finance.cancel_residual_orders', reads: ['execution_id'], writes: ['residual_cancelled', 'cancellation_reference'], config: { compensates: ['reconcile'] } },
    { id: 'exception_join', kind: 'join', label: 'Join exception response', description: 'Wait for escalation and cancellation evidence.', reads: ['residual_cancelled', 'cancellation_reference'], writes: [], config: { mode: 'all' } },
    { id: 'publish_reconciliation', kind: 'function', label: 'Publish reconciliation', description: 'Hand matched or exception evidence to books and records.', handler: 'quantitative_finance.publish_reconciliation', reads: ['execution_id', 'strategy_id', 'account_id', 'reconciliation', 'residual_cancelled', 'cancellation_reference'], writes: ['reconciliation_record'], config: { roleId: 'operations_analyst', toolIds: ['reconciliation_write'] } },
  ],
  edges: [
    { id: 'start.normalize', source: 'start', target: 'normalize_execution', on: 'success' },
    { id: 'normalize.reconcile', source: 'normalize_execution', target: 'reconcile', on: 'success' },
    { id: 'reconcile.route', source: 'reconcile', target: 'route_reconciliation', on: 'success' },
    { id: 'route.publish', source: 'route_reconciliation', target: 'publish_reconciliation', on: 'success', condition: { field: 'reconciliation_matched', operator: 'equals', value: true } },
    { id: 'route.escalate', source: 'route_reconciliation', target: 'escalate_exception', on: 'success', condition: { field: 'reconciliation_matched', operator: 'equals', value: false } },
    { id: 'route.cancel', source: 'route_reconciliation', target: 'cancel_residual', on: 'success', condition: { field: 'reconciliation_matched', operator: 'equals', value: false } },
    { id: 'escalate.join', source: 'escalate_exception', target: 'exception_join', on: 'success' },
    { id: 'cancel.join', source: 'cancel_residual', target: 'exception_join', on: 'success' },
    { id: 'join.publish', source: 'exception_join', target: 'publish_reconciliation', on: 'success' },
  ],
  budget,
};

const stringField = (description: string) => ({ type: 'string' as const, required: true, description });

export const quantitativeFinancePack: IndustryPackManifest = {
  id: 'quantitative_finance', version: '0.6.0', name: 'Quantitative Finance Governance Pack', license: 'MIT',
  description: 'A governed research-to-order and fill-reconciliation workflow. It keeps market data, backtesting, OMS/EMS, broker routing and books-and-records in specialist systems while preserving evidence, limits, approvals, intent, fills and exceptions as connected context.',
  ontology: {
    objectTypes: [
      { id: 'strategy_mandate', label: 'Strategy mandate', description: 'Objective, universe, capital and limits.', fields: { strategy_id: stringField('Strategy identifier.'), objective: stringField('Mandate objective.'), benchmark: stringField('Benchmark.'), as_of: stringField('Point-in-time date.') } },
      { id: 'research_hypothesis', label: 'Research hypothesis', description: 'A falsifiable signal thesis.', fields: { statement: stringField('Hypothesis statement.'), signal_family: stringField('Signal family.'), falsification: stringField('Falsification rule.') } },
      { id: 'backtest_evidence', label: 'Backtest evidence', description: 'Point-in-time simulation evidence.', fields: { instrument: stringField('Instrument.'), sharpe: { type: 'number', required: true, description: 'Sharpe ratio.' }, max_drawdown: { type: 'number', required: true, description: 'Maximum drawdown.' }, evidence_uri: stringField('Evidence locator.') } },
      { id: 'portfolio_proposal', label: 'Portfolio proposal', description: 'Target portfolio before order creation.', fields: { strategy_id: stringField('Strategy.'), targets: { type: 'array', required: true, description: 'Target weights.' } } },
      { id: 'risk_assessment', label: 'Risk assessment', description: 'Independent limit and stress evidence.', fields: { passed: { type: 'boolean', required: true, description: 'Risk result.' }, stress_loss_99: { type: 'number', required: true, description: '99% stress loss.' }, model_risk: stringField('Model-risk disclosure.') } },
      { id: 'approval_decision', label: 'Approval decision', description: 'Risk, compliance or execution authorization.', fields: { gate: stringField('Approval gate.'), approved: { type: 'boolean', required: true, description: 'Decision.' } } },
      { id: 'order_intent', label: 'Order intent', description: 'Approved account-scoped intent before external routing.', fields: { strategy_id: stringField('Strategy.'), account_id: stringField('Account.'), orders: { type: 'array', required: true, description: 'Orders.' } } },
      { id: 'execution', label: 'Execution', description: 'External OMS request and observed fills.', fields: { execution_id: stringField('Execution identifier.'), account_id: stringField('Account.'), status: stringField('Execution status.') } },
      { id: 'fill', label: 'Fill', description: 'Immutable observed fill.', fields: { instrument: stringField('Instrument.'), notional_usd: { type: 'number', required: true, description: 'Filled notional.' }, status: stringField('Fill status.') } },
      { id: 'reconciliation', label: 'Reconciliation', description: 'Expected-versus-observed books evidence.', fields: { matched: { type: 'boolean', required: true, description: 'Match result.' }, variance_usd: { type: 'number', required: true, description: 'Notional variance.' } } },
      { id: 'execution_exception', label: 'Execution exception', description: 'Mismatch and safe response evidence.', fields: { execution_id: stringField('Execution.'), residual_cancelled: { type: 'boolean', required: true, description: 'Residual cancellation.' }, evidence_uri: stringField('Recovery evidence.') } },
      { id: 'finance_record', label: 'Finance record', description: 'Portable governance or reconciliation record.', fields: { record_type: stringField('Record type.'), content: stringField('Markdown content.') } },
    ],
    relationTypes: [
      { id: 'governs_strategy', label: 'Governs strategy', description: 'Mandate governs hypothesis.', sourceTypes: ['strategy_mandate'], targetTypes: ['research_hypothesis'] },
      { id: 'tests_hypothesis', label: 'Tests hypothesis', description: 'Backtest tests hypothesis.', sourceTypes: ['backtest_evidence'], targetTypes: ['research_hypothesis'] },
      { id: 'supports_portfolio', label: 'Supports portfolio', description: 'Evidence supports proposal.', sourceTypes: ['backtest_evidence'], targetTypes: ['portfolio_proposal'] },
      { id: 'evaluates_portfolio', label: 'Evaluates portfolio', description: 'Risk evaluates proposal.', sourceTypes: ['risk_assessment'], targetTypes: ['portfolio_proposal'] },
      { id: 'authorizes_intent', label: 'Authorizes intent', description: 'Decisions authorize order intent.', sourceTypes: ['approval_decision'], targetTypes: ['order_intent'] },
      { id: 'implements_portfolio', label: 'Implements portfolio', description: 'Order intent implements proposal.', sourceTypes: ['order_intent'], targetTypes: ['portfolio_proposal'] },
      { id: 'submitted_as', label: 'Submitted as', description: 'Intent is submitted as execution.', sourceTypes: ['order_intent'], targetTypes: ['execution'] },
      { id: 'fills_execution', label: 'Fills execution', description: 'Fills belong to execution.', sourceTypes: ['fill'], targetTypes: ['execution'] },
      { id: 'reconciles_execution', label: 'Reconciles execution', description: 'Reconciliation verifies execution.', sourceTypes: ['reconciliation'], targetTypes: ['execution'] },
      { id: 'raises_exception', label: 'Raises exception', description: 'Mismatch raises exception.', sourceTypes: ['reconciliation'], targetTypes: ['execution_exception'] },
      { id: 'documents_finance_work', label: 'Documents finance work', description: 'Record documents governed work.', sourceTypes: ['finance_record'], targetTypes: ['strategy_mandate', 'execution', 'reconciliation'] },
    ],
  },
  roles: [
    { id: 'quant_researcher', label: 'Quant researcher', mission: 'Produce reproducible point-in-time evidence.', allowedTools: ['market_data_read', 'backtest_execute'], forbiddenActions: ['Submit live orders', 'Approve own model risk'] },
    { id: 'portfolio_manager', label: 'Portfolio manager', mission: 'Translate evidence into mandate-aligned targets.', allowedTools: [], forbiddenActions: ['Override risk limits'] },
    { id: 'risk_manager', label: 'Independent risk manager', mission: 'Evaluate exposure, stress loss and model risk independently.', allowedTools: ['risk_engine_read'], forbiddenActions: ['Submit orders'] },
    { id: 'compliance_officer', label: 'Compliance officer', mission: 'Approve restrictions and intended execution.', allowedTools: [], forbiddenActions: ['Alter research evidence'] },
    { id: 'execution_trader', label: 'Execution trader', mission: 'Authorize and submit account-scoped intent.', allowedTools: ['order_submit'], forbiddenActions: ['Change approved portfolio weights'] },
    { id: 'operations_analyst', label: 'Trading operations analyst', mission: 'Reconcile fills and resolve operational exceptions.', allowedTools: ['fill_read', 'reconciliation_write'], forbiddenActions: ['Rewrite immutable fills'] },
  ],
  tools: [
    { id: 'market_data_read', label: 'Market data query', risk: 'read', description: 'Read point-in-time market data.', operation: 'query', inputSchema: { type: 'object', properties: { instruments: { type: 'array', items: { type: 'string' } }, as_of: { type: 'string' } }, required: ['instruments', 'as_of'], additionalProperties: false }, outputSchema: { type: 'object', properties: { snapshot_id: { type: 'string' }, status: { type: 'string' } }, required: ['snapshot_id', 'status'], additionalProperties: false }, idempotency: 'intrinsic' },
    { id: 'backtest_execute', label: 'Backtest engine', risk: 'draft', description: 'Run a specialist point-in-time simulation.', operation: 'query', inputSchema: { type: 'object', properties: { instrument: { type: 'string' }, as_of: { type: 'string' } }, required: ['instrument', 'as_of'], additionalProperties: false }, outputSchema: { type: 'object', properties: { run_id: { type: 'string' }, evidence_uri: { type: 'string' } }, required: ['run_id', 'evidence_uri'], additionalProperties: false }, idempotency: 'intrinsic' },
    { id: 'risk_engine_read', label: 'Risk engine query', risk: 'read', description: 'Read exposure and stress metrics.', operation: 'query', inputSchema: { type: 'object', properties: { strategy_id: { type: 'string' } }, required: ['strategy_id'], additionalProperties: false }, outputSchema: { type: 'object', properties: { risk_snapshot_id: { type: 'string' }, status: { type: 'string' } }, required: ['risk_snapshot_id', 'status'], additionalProperties: false }, idempotency: 'intrinsic' },
    { id: 'order_submit', label: 'OMS order submission', risk: 'external', description: 'Submit approved intent to the external OMS.', operation: 'command', inputSchema: { type: 'object', properties: { idempotency_key: { type: 'string' }, account_id: { type: 'string' }, orders: { type: 'array' } }, required: ['idempotency_key', 'account_id', 'orders'], additionalProperties: false }, outputSchema: { type: 'object', properties: { execution_id: { type: 'string' }, status: { type: 'string' } }, required: ['execution_id', 'status'], additionalProperties: false }, idempotency: 'keyed', idempotencyKeyField: 'idempotency_key' },
    { id: 'fill_read', label: 'Fill query', risk: 'read', description: 'Read immutable broker or OMS fills.', operation: 'query', inputSchema: { type: 'object', properties: { execution_id: { type: 'string' } }, required: ['execution_id'], additionalProperties: false }, outputSchema: { type: 'object', properties: { fills: { type: 'array' } }, required: ['fills'], additionalProperties: false }, idempotency: 'intrinsic' },
    { id: 'reconciliation_write', label: 'Books reconciliation writer', risk: 'write', description: 'Write reconciliation evidence to books and records.', operation: 'command', inputSchema: { type: 'object', properties: { idempotency_key: { type: 'string' }, execution_id: { type: 'string' }, matched: { type: 'boolean' } }, required: ['idempotency_key', 'execution_id', 'matched'], additionalProperties: false }, outputSchema: { type: 'object', properties: { record_id: { type: 'string' }, status: { type: 'string' } }, required: ['record_id', 'status'], additionalProperties: false }, idempotency: 'keyed', idempotencyKeyField: 'idempotency_key' },
  ],
  graphs: [strategyGraph, backtestGraph, reconciliationGraph],
  evaluations: [
    { id: 'research_validity', label: 'Research validity', description: 'Requires complete point-in-time and out-of-sample evidence.', blocking: true },
    { id: 'risk_limits', label: 'Risk limits', description: 'Requires portfolio and stress metrics inside mandate.', blocking: true },
    { id: 'risk_approval', label: 'Risk approval', description: 'Requires accountable independent risk acceptance.', blocking: true },
    { id: 'compliance_approval', label: 'Compliance approval', description: 'Requires accountable compliance acceptance.', blocking: true },
    { id: 'execution_authorization', label: 'Execution authorization', description: 'Requires final account-scoped intent approval.', blocking: true },
    { id: 'reconciliation_integrity', label: 'Reconciliation integrity', description: 'Requires fills to match approved expected notional.', blocking: true },
  ],
  deliverables: [
    { id: 'strategy_execution_record', label: 'Strategy execution governance record', description: 'Research, risk, approval and OMS handoff record.', graphId: strategyGraph.id, stateField: 'strategy_execution_record', mediaType: 'text/markdown', artifactType: 'strategy_governance_record', evidenceFields: ['research_summary', 'risk_assessment', 'order_intent', 'execution_request'], approvalField: 'execution_approved' },
    { id: 'reconciliation_record', label: 'Execution reconciliation record', description: 'Matched books or controlled exception evidence.', graphId: reconciliationGraph.id, stateField: 'reconciliation_record', mediaType: 'text/markdown', artifactType: 'execution_reconciliation_record', evidenceFields: ['execution_observation', 'reconciliation'] },
  ],
  fixtures: [
    { id: 'market_neutral_research', label: 'Market-neutral strategy release', description: 'Exercises research fan-out and three independent approvals.', graphId: strategyGraph.id, input: { strategy_id: 'equity.market_neutral.v1', account_id: 'paper.us-equities', objective: 'Construct a diversified market-neutral equity portfolio', universe: ['AAPL', 'MSFT', 'NVDA', 'AMZN'], benchmark: 'USD-SOFR', capital_usd: 5_000_000, constraints: { max_drawdown: 0.25, max_gross_exposure: 1.2 }, as_of: '2026-08-11' }, decisions: { risk_approval: true, compliance_approval: true, execution_approval: true }, expectations: [
      { field: 'backtest_results', operator: 'min_items', value: 4, description: 'Produces per-instrument evidence.' },
      { field: 'execution_request', operator: 'exists', description: 'Creates an external OMS request.' },
      { field: 'strategy_execution_record', operator: 'includes', value: 'Governed strategy release', description: 'Publishes the governance record.' },
    ] },
    { id: 'risk_rejected_strategy', label: 'Risk-rejected strategy', description: 'Proves that rejected risk cannot reach order creation.', graphId: strategyGraph.id, input: { strategy_id: 'equity.concentrated.v1', account_id: 'paper.us-equities', objective: 'Evaluate a concentrated factor portfolio', universe: ['AAPL', 'NVDA'], benchmark: 'SPY', capital_usd: 1_000_000, constraints: { max_drawdown: 0.05, max_gross_exposure: 1 }, as_of: '2026-08-11' }, decisions: { risk_approval: false }, expectations: [
      { field: 'risk_approved', operator: 'equals', value: false, description: 'Preserves the risk decision.' },
      { field: 'rejection_reason', operator: 'includes', value: 'Independent risk rejected', description: 'Stops before compliance and orders.' },
    ] },
    { id: 'matched_fills', label: 'Matched fill reconciliation', description: 'Simulates a complete execution that reconciles.', graphId: reconciliationGraph.id, input: { execution_id: 'exec-1001', strategy_id: 'equity.market_neutral.v1', account_id: 'paper.us-equities', fills: [{ instrument: 'AAPL', notional_usd: 500000, status: 'filled' }, { instrument: 'MSFT', notional_usd: 500000, status: 'filled' }], expected_notional_usd: 1_000_000, observed_at: '2026-08-11T20:00:00.000Z' }, decisions: {}, expectations: [
      { field: 'reconciliation_matched', operator: 'equals', value: true, description: 'Matches expected notional.' },
      { field: 'reconciliation_record', operator: 'includes', value: 'Outcome: matched', description: 'Publishes matched books evidence.' },
    ] },
    { id: 'fill_mismatch_exception', label: 'Fill mismatch exception', description: 'Simulates partial fills, escalation and residual cancellation.', graphId: reconciliationGraph.id, input: { execution_id: 'exec-1002', strategy_id: 'equity.market_neutral.v1', account_id: 'paper.us-equities', fills: [{ instrument: 'AAPL', notional_usd: 400000, status: 'filled' }, { instrument: 'MSFT', notional_usd: 350000, status: 'partial' }], expected_notional_usd: 1_000_000, observed_at: '2026-08-11T20:05:00.000Z' }, decisions: {}, expectations: [
      { field: 'reconciliation_matched', operator: 'equals', value: false, description: 'Detects fill mismatch.' },
      { field: 'residual_cancelled', operator: 'equals', value: true, description: 'Cancels residual open orders.' },
      { field: 'reconciliation_record', operator: 'includes', value: 'Outcome: exception', description: 'Publishes exception evidence.' },
    ] },
  ],
};
