import type { IndustryPackManifest } from '@graph-native/contracts';

export const researchPack: IndustryPackManifest = {
  id: 'research',
  version: '0.1.0',
  name: 'Cross-industry Research Pack',
  description:
    'A zero-key reference Pack that can optionally use a selected model for synthesis while preserving evidence, quality review, human approval, and a publishable deliverable.',
  license: 'MIT',
  ontology: {
    objectTypes: [
      {
        id: 'research_brief',
        label: 'Research brief',
        description: 'The normalized intent, scope, and acceptance criteria for a research run.',
        fields: {
          goal: { type: 'string', required: true, description: 'The research goal.' },
          scope: { type: 'string', required: true, description: 'The bounded research scope.' },
        },
      },
      {
        id: 'evidence',
        label: 'Evidence',
        description: 'A traceable observation collected from a source.',
        fields: {
          claim: { type: 'string', required: true, description: 'The supported claim.' },
          source: { type: 'string', required: true, description: 'The evidence source.' },
        },
      },
      {
        id: 'deliverable',
        label: 'Deliverable',
        description: 'A reviewed output assembled from evidence and decisions.',
        fields: {
          content: { type: 'string', required: true, description: 'The final deliverable content.' },
          approved: { type: 'boolean', required: true, description: 'Human approval state.' },
        },
      },
      {
        id: 'decision',
        label: 'Decision',
        description: 'A human or automated quality-gate decision.',
        fields: {
          approved: { type: 'boolean', required: true, description: 'Whether work may advance.' },
          rationale: { type: 'string', required: false, description: 'Why the decision was made.' },
        },
      },
      {
        id: 'model_call',
        label: 'Model call',
        description: 'The provider, model and usage metadata for a governed Agent execution.',
        fields: {
          provider_id: { type: 'string', required: true, description: 'Selected provider identifier.' },
          protocol: { type: 'string', required: true, description: 'Provider protocol used by the call.' },
          model: { type: 'string', required: true, description: 'Resolved model identifier.' },
          input_tokens: { type: 'number', required: false, description: 'Reported input token count.' },
          output_tokens: { type: 'number', required: false, description: 'Reported output token count.' },
          latency_ms: { type: 'number', required: false, description: 'Observed request latency.' },
          request_id: { type: 'string', required: false, description: 'Provider request identifier.' },
        },
      },
    ],
    relationTypes: [
      {
        id: 'scoped_by',
        label: 'Scoped by',
        description: 'Evidence was gathered under a research brief.',
        sourceTypes: ['evidence'],
        targetTypes: ['research_brief'],
      },
      {
        id: 'supports',
        label: 'Supports',
        description: 'Evidence supports a deliverable.',
        sourceTypes: ['evidence'],
        targetTypes: ['deliverable'],
      },
      {
        id: 'governs',
        label: 'Governs',
        description: 'A decision governs whether a deliverable can be published.',
        sourceTypes: ['decision'],
        targetTypes: ['deliverable'],
      },
      {
        id: 'contributed_to',
        label: 'Contributed to',
        description: 'A governed model call contributed to a reviewed deliverable.',
        sourceTypes: ['model_call'],
        targetTypes: ['deliverable'],
      },
    ],
  },
  roles: [
    {
      id: 'researcher',
      label: 'Researcher',
      mission: 'Gather attributable evidence without inventing unsupported claims.',
      allowedTools: ['source_search', 'document_read'],
      forbiddenActions: ['Publishing unreviewed work', 'Removing source attribution'],
    },
    {
      id: 'reviewer',
      label: 'Reviewer',
      mission: 'Check evidence coverage and decide whether the deliverable is ready.',
      allowedTools: ['document_read'],
      forbiddenActions: ['Changing source material during review'],
    },
  ],
  tools: [
    {
      id: 'source_search',
      label: 'Source search',
      risk: 'read',
      description: 'Search approved evidence sources.',
    },
    {
      id: 'document_read',
      label: 'Document read',
      risk: 'read',
      description: 'Read a document without mutating it.',
    },
  ],
  evaluations: [
    {
      id: 'evidence_coverage',
      label: 'Evidence coverage',
      description: 'Every conclusion must be backed by at least one attributable evidence item.',
      blocking: true,
    },
    {
      id: 'human_approval',
      label: 'Human approval',
      description: 'A reviewer must approve the synthesized deliverable before publication.',
      blocking: true,
    },
  ],
  deliverables: [
    {
      id: 'approved_research',
      label: 'Approved research deliverable',
      description: 'A reviewed Markdown synthesis with attributable evidence.',
      graphId: 'research.workflow',
      stateField: 'deliverable',
      mediaType: 'text/markdown',
    },
  ],
  fixtures: [
    {
      id: 'graph_native_question',
      label: 'Graph-native infrastructure question',
      description: 'Proves the zero-key research path, evidence gate, approval, and publication.',
      graphId: 'research.workflow',
      input: { goal: 'Can governed work graphs support reusable industry workflows?' },
      decisions: { approval: true },
      expectations: [
        {
          field: 'review_status',
          operator: 'includes',
          value: 'passed:',
          description: 'The deterministic evidence coverage gate passes.',
        },
        {
          field: 'deliverable',
          operator: 'includes',
          value: '# Approved research deliverable',
          description: 'The Pack produces its declared Markdown deliverable.',
        },
      ],
    },
  ],
  graphs: [
    {
      id: 'research.workflow',
      version: 1,
      name: 'Evidence-backed research workflow',
      description:
        'Normalizes a goal, gathers two independent evidence streams in parallel, synthesizes and verifies the result, then pauses for human approval.',
      state: {
        fields: {
          goal: { type: 'string', required: true, description: 'User-provided research goal.' },
          brief: { type: 'string', required: false, description: 'Normalized research brief.' },
          market_evidence: { type: 'array', required: false, description: 'Market evidence stream.' },
          technology_evidence: {
            type: 'array',
            required: false,
            description: 'Technology evidence stream.',
          },
          synthesis: { type: 'string', required: false, description: 'Evidence synthesis.' },
          review_status: { type: 'string', required: false, description: 'Automated review result.' },
          approved: { type: 'boolean', required: false, description: 'Human approval decision.' },
          deliverable: { type: 'string', required: false, description: 'Final published output.' },
          rejection_reason: { type: 'string', required: false, description: 'Reason work stopped.' },
        },
      },
      nodes: [
        {
          id: 'start',
          kind: 'trigger',
          label: 'Start',
          description: 'Accept a research goal.',
          reads: ['goal'],
          writes: [],
          config: {},
        },
        {
          id: 'normalize_brief',
          kind: 'function',
          label: 'Normalize brief',
          description: 'Turn the goal into a bounded brief.',
          handler: 'research.normalize_brief',
          reads: ['goal'],
          writes: ['brief'],
          config: {},
        },
        {
          id: 'market_research',
          kind: 'agent',
          label: 'Market research',
          description: 'Gather market and adoption evidence.',
          handler: 'research.market_evidence',
          reads: ['brief'],
          writes: ['market_evidence'],
          config: { roleId: 'researcher', toolIds: ['source_search', 'document_read'] },
        },
        {
          id: 'technology_research',
          kind: 'agent',
          label: 'Technology research',
          description: 'Gather implementation and technical-risk evidence.',
          handler: 'research.technology_evidence',
          reads: ['brief'],
          writes: ['technology_evidence'],
          config: { roleId: 'researcher', toolIds: ['source_search', 'document_read'] },
        },
        {
          id: 'evidence_join',
          kind: 'join',
          label: 'Join evidence',
          description: 'Wait for both independent evidence streams.',
          reads: ['market_evidence', 'technology_evidence'],
          writes: [],
          config: { mode: 'all' },
        },
        {
          id: 'synthesize',
          kind: 'agent',
          label: 'Synthesize',
          description: 'Create a concise evidence-backed conclusion.',
          handler: 'research.synthesize',
          reads: ['brief', 'market_evidence', 'technology_evidence'],
          writes: ['synthesis'],
          config: {
            roleId: 'researcher',
            modelInstructions: 'Write a concise synthesis grounded only in the supplied market_evidence and technology_evidence. Preserve every source locator and return a JSON object with a single synthesis string.',
          },
        },
        {
          id: 'quality_check',
          kind: 'function',
          label: 'Quality check',
          description: 'Verify that both evidence streams are present.',
          handler: 'research.quality_check',
          reads: ['market_evidence', 'technology_evidence', 'synthesis'],
          writes: ['review_status'],
          config: { evaluationId: 'evidence_coverage' },
        },
        {
          id: 'approval',
          kind: 'human',
          label: 'Human approval',
          description: 'Pause until a reviewer approves or rejects publication.',
          reads: ['synthesis', 'review_status'],
          writes: ['approved'],
          config: { decisionField: 'approved', roleId: 'reviewer' },
        },
        {
          id: 'approval_route',
          kind: 'router',
          label: 'Route approval',
          description: 'Route approved and rejected work.',
          reads: ['approved'],
          writes: [],
          config: {},
        },
        {
          id: 'publish',
          kind: 'function',
          label: 'Publish deliverable',
          description: 'Package the approved synthesis as a deliverable.',
          handler: 'research.publish',
          reads: ['synthesis', 'review_status', 'approved'],
          writes: ['deliverable'],
          config: {},
        },
        {
          id: 'record_rejection',
          kind: 'function',
          label: 'Record rejection',
          description: 'Record why the workflow stopped.',
          handler: 'research.record_rejection',
          reads: ['review_status', 'approved'],
          writes: ['rejection_reason'],
          config: {},
        },
      ],
      edges: [
        { id: 'e_start_brief', source: 'start', target: 'normalize_brief', on: 'success' },
        { id: 'e_brief_market', source: 'normalize_brief', target: 'market_research', on: 'success' },
        {
          id: 'e_brief_technology',
          source: 'normalize_brief',
          target: 'technology_research',
          on: 'success',
        },
        { id: 'e_market_join', source: 'market_research', target: 'evidence_join', on: 'success' },
        {
          id: 'e_technology_join',
          source: 'technology_research',
          target: 'evidence_join',
          on: 'success',
        },
        { id: 'e_join_synthesis', source: 'evidence_join', target: 'synthesize', on: 'success' },
        { id: 'e_synthesis_quality', source: 'synthesize', target: 'quality_check', on: 'success' },
        { id: 'e_quality_approval', source: 'quality_check', target: 'approval', on: 'success' },
        { id: 'e_approval_route', source: 'approval', target: 'approval_route', on: 'success' },
        {
          id: 'e_route_publish',
          source: 'approval_route',
          target: 'publish',
          on: 'success',
          condition: { field: 'approved', operator: 'equals', value: true },
          label: 'Approved',
        },
        {
          id: 'e_route_reject',
          source: 'approval_route',
          target: 'record_rejection',
          on: 'success',
          condition: { field: 'approved', operator: 'equals', value: false },
          label: 'Rejected',
        },
      ],
      budget: { maxSteps: 32, maxDurationMs: 60_000, maxConcurrency: 4 },
    },
  ],
};
