import type { IndustryPackManifest } from '@graph-native/contracts';

export const architecturePack: IndustryPackManifest = {
  id: 'architecture',
  version: '0.2.0',
  name: 'Architecture Concept Design Pack',
  description:
    'An evidence-backed workflow that turns project requirements, site context, constraints, and source material into reviewed concept directions and a traceable design brief.',
  license: 'MIT',
  ontology: {
    objectTypes: [
      {
        id: 'project_brief',
        label: 'Project brief',
        description: 'The normalized project intent and design scope.',
        fields: {
          project_name: { type: 'string', required: true, description: 'Project name.' },
          project_type: { type: 'string', required: true, description: 'Project type.' },
          site_context: { type: 'string', required: true, description: 'Site and urban context.' },
          goals: { type: 'array', required: true, description: 'Confirmed client goals.' },
        },
      },
      {
        id: 'source_evidence',
        label: 'Source evidence',
        description: 'A source claim with a stable locator.',
        fields: {
          source: { type: 'string', required: true, description: 'Source name or URI.' },
          locator: { type: 'string', required: true, description: 'Page, line, region, or other locator.' },
          claim: { type: 'string', required: true, description: 'Claim supported by the source.' },
        },
      },
      {
        id: 'requirement',
        label: 'Requirement',
        description: 'A design requirement derived from the project intake.',
        fields: {
          statement: { type: 'string', required: true, description: 'Requirement statement.' },
          category: { type: 'string', required: true, description: 'Stable requirement category.' },
        },
      },
      {
        id: 'constraint',
        label: 'Constraint',
        description: 'A boundary that concept directions must respect.',
        fields: {
          statement: { type: 'string', required: true, description: 'Constraint statement.' },
          status: { type: 'string', required: true, description: 'Confirmation status.' },
        },
      },
      {
        id: 'analysis_finding',
        label: 'Analysis finding',
        description: 'An evidence-aware site or program conclusion and its design impact.',
        fields: {
          discipline: { type: 'string', required: true, description: 'Analysis discipline.' },
          statement: { type: 'string', required: true, description: 'Finding statement.' },
          design_impact: { type: 'string', required: true, description: 'Impact on concept design.' },
        },
      },
      {
        id: 'design_direction',
        label: 'Design direction',
        description: 'A distinct, reviewable concept direction.',
        fields: {
          name: { type: 'string', required: true, description: 'Direction name.' },
          thesis: { type: 'string', required: true, description: 'Core design thesis.' },
          strategies: { type: 'array', required: true, description: 'Spatial and program strategies.' },
          risks: { type: 'array', required: true, description: 'Known risks and assumptions.' },
        },
      },
      {
        id: 'decision',
        label: 'Design decision',
        description: 'A recorded human approval or rejection.',
        fields: {
          approved: { type: 'boolean', required: true, description: 'Approval state.' },
          rationale: { type: 'string', required: true, description: 'Decision rationale.' },
        },
      },
      {
        id: 'deliverable',
        label: 'Concept design brief',
        description: 'A reviewed deliverable assembled from the same graph facts.',
        fields: {
          title: { type: 'string', required: true, description: 'Deliverable title.' },
          content: { type: 'string', required: true, description: 'Markdown content.' },
          format: { type: 'string', required: true, description: 'Media type.' },
        },
      },
    ],
    relationTypes: [
      {
        id: 'brief_contains',
        label: 'Brief contains',
        description: 'The project brief contains a requirement or constraint.',
        sourceTypes: ['project_brief'],
        targetTypes: ['requirement', 'constraint'],
      },
      {
        id: 'evidence_supports',
        label: 'Evidence supports',
        description: 'Source evidence supports a requirement, constraint, or analysis finding.',
        sourceTypes: ['source_evidence'],
        targetTypes: ['requirement', 'constraint', 'analysis_finding'],
      },
      {
        id: 'finding_informs',
        label: 'Finding informs',
        description: 'An analysis finding informs a design direction.',
        sourceTypes: ['analysis_finding'],
        targetTypes: ['design_direction'],
      },
      {
        id: 'constraint_governs',
        label: 'Constraint governs',
        description: 'A constraint governs a design direction.',
        sourceTypes: ['constraint'],
        targetTypes: ['design_direction'],
      },
      {
        id: 'decision_governs',
        label: 'Decision governs',
        description: 'A human decision governs publication of the deliverable.',
        sourceTypes: ['decision'],
        targetTypes: ['deliverable'],
      },
      {
        id: 'deliverable_includes',
        label: 'Deliverable includes',
        description: 'A confirmed design direction or finding is included in the deliverable.',
        sourceTypes: ['analysis_finding', 'design_direction'],
        targetTypes: ['deliverable'],
      },
    ],
  },
  roles: [
    {
      id: 'project_analyst',
      label: 'Project analyst',
      mission: 'Separate sourced project facts, design requirements, assumptions, and unresolved gaps.',
      allowedTools: ['source_read', 'site_reference_read'],
      forbiddenActions: ['Presenting an unsupported assumption as a confirmed constraint'],
    },
    {
      id: 'design_strategist',
      label: 'Design strategist',
      mission: 'Develop distinct concept directions grounded in project evidence and constraints.',
      allowedTools: ['source_read', 'site_reference_read'],
      forbiddenActions: ['Claiming code compliance or constructability without specialist review'],
    },
    {
      id: 'design_reviewer',
      label: 'Design reviewer',
      mission: 'Review evidence coverage, option distinction, risk disclosure, and delivery readiness.',
      allowedTools: ['source_read'],
      forbiddenActions: ['Approving work with a failed blocking quality gate'],
    },
  ],
  tools: [
    {
      id: 'source_read',
      label: 'Source read',
      risk: 'read',
      description: 'Read an approved project source without changing it.',
    },
    {
      id: 'site_reference_read',
      label: 'Site reference read',
      risk: 'read',
      description: 'Read an approved map, photograph, or site record.',
    },
  ],
  evaluations: [
    {
      id: 'evidence_coverage',
      label: 'Evidence coverage',
      description: 'The workflow has attributable sources and explicit project constraints.',
      blocking: true,
    },
    {
      id: 'option_distinction',
      label: 'Option distinction',
      description: 'At least two concept directions have different theses and disclosed risks.',
      blocking: true,
    },
    {
      id: 'human_approval',
      label: 'Human approval',
      description: 'A design reviewer approves the concept brief before publication.',
      blocking: true,
    },
  ],
  deliverables: [
    {
      id: 'concept_design_brief',
      label: 'Concept design brief',
      description: 'An evidence-backed Markdown brief containing boundaries, findings, options, and recommendation.',
      graphId: 'architecture.concept_workflow',
      stateField: 'deliverable',
      mediaType: 'text/markdown',
    },
  ],
  fixtures: [
    {
      id: 'street_renewal',
      label: 'Street renewal concept',
      description: 'A small adaptive-reuse and commercial activation concept study.',
      graphId: 'architecture.concept_workflow',
      input: {
        project_name: '长宁街区更新',
        project_type: 'adaptive_reuse_commercial',
        output_language: 'zh-CN',
        site_context: '现有社区商业街区的街角入口隐蔽，沿街界面零散，夜间识别度和公共活力不足。',
        client_goals: [
          '在街角形成具有识别度的社区会客空间。',
          '在不影响现有商户经营的前提下改善夜间活力。',
          '通过兼顾成本的分期改造尽快形成可见变化。',
        ],
        constraints: [
          '保留现有主体结构和受保护的沿街骑楼。',
          '顾客流线与餐饮后勤流线必须分离。',
          '夜间营业时段和噪声边界尚待确认。',
        ],
        evidence: [
          { source: '设计任务书.pdf', locator: '第 4 页', claim: '业主优先关注面向公众的可见更新。' },
          { source: '甲方会议纪要.md', locator: '第 18–24 行', claim: '分期改造期间现有商户需要保持营业。' },
          { source: '现场照片-03.jpg', locator: '西北街角', claim: '现状主入口从主要步行来向不可见。' },
          { source: '规划条件.pdf', locator: '第 12 页', claim: '现有沿街骑楼被明确要求保留。' },
        ],
      },
      decisions: { approval: true },
      expectations: [
        { field: 'evidence_audit', operator: 'exists', description: 'Creates an evidence coverage audit.' },
        { field: 'concept_directions', operator: 'min_items', value: 2, description: 'Produces at least two distinct directions.' },
        { field: 'review_status', operator: 'includes', value: 'passed:', description: 'Passes the blocking quality gate.' },
        { field: 'deliverable', operator: 'includes', value: '# 概念设计简报', description: 'Produces the declared Markdown brief.' },
      ],
    },
    {
      id: 'transit_culture_hub',
      label: 'Transit culture hub',
      description: 'A transit-oriented cultural and commercial concept study.',
      graphId: 'architecture.concept_workflow',
      input: {
        project_name: 'Hongqiao Culture Hub',
        project_type: 'transit_oriented_cultural_commercial',
        output_language: 'en-US',
        site_context: 'A mixed-use site connects a rail concourse, a public-space axis, and a future cultural venue across strong level changes.',
        client_goals: [
          'Turn transfer footfall into an all-day public cultural destination.',
          'Create a legible route between rail, public space, and cultural programs.',
          'Support independent nighttime operation for food and performance uses.',
        ],
        constraints: [
          'Building height must not exceed 60 meters.',
          'The north-south public-space view corridor must remain continuous.',
          'The final underground rail connection location remains subject to approval.',
        ],
        evidence: [
          { source: 'control-plan.pdf', locator: 'p.22', claim: 'The plot ratio limit is 3.5 and the height limit is 60 meters.' },
          { source: 'control-plan.pdf', locator: 'p.34', claim: 'The site sits on a protected public-space view corridor.' },
          { source: 'mobility-study.pdf', locator: 'p.46', claim: 'Pedestrian arrival is concentrated at the northern concourse edge.' },
          { source: 'operations-brief.pdf', locator: 'p.17', claim: 'Food and performance venues require independent evening access.' },
        ],
      },
      decisions: { approval: true },
      expectations: [
        { field: 'site_findings', operator: 'min_items', value: 2, description: 'Produces site and movement findings.' },
        { field: 'program_findings', operator: 'min_items', value: 2, description: 'Produces program and operation findings.' },
        { field: 'deliverable', operator: 'includes', value: '## Source register', description: 'Keeps a visible source register.' },
      ],
    },
  ],
  graphs: [
    {
      id: 'architecture.concept_workflow',
      version: 1,
      name: 'Evidence-backed concept design workflow',
      description: 'Normalize a brief, audit evidence, analyze site and program in parallel, develop and evaluate options, pause for review, and publish a traceable concept brief.',
      state: {
        fields: {
          project_name: { type: 'string', required: true, description: 'Project name.' },
          project_type: { type: 'string', required: true, description: 'Project type.' },
          output_language: { type: 'string', required: false, description: 'Requested deliverable language.' },
          site_context: { type: 'string', required: true, description: 'Site and urban context.' },
          client_goals: { type: 'array', required: true, description: 'Client and user goals.' },
          constraints: { type: 'array', required: true, description: 'Known and pending constraints.' },
          evidence: { type: 'array', required: true, description: 'Attributable source claims.' },
          normalized_brief: { type: 'object', required: false, description: 'Normalized design brief.' },
          evidence_audit: { type: 'object', required: false, description: 'Evidence coverage and gaps.' },
          site_findings: { type: 'array', required: false, description: 'Site and urban analysis findings.' },
          program_findings: { type: 'array', required: false, description: 'Program and operation findings.' },
          concept_directions: { type: 'array', required: false, description: 'Distinct concept directions.' },
          option_evaluation: { type: 'object', required: false, description: 'Comparable direction scores and recommendation.' },
          review_status: { type: 'string', required: false, description: 'Blocking quality-gate result.' },
          approved: { type: 'boolean', required: false, description: 'Human approval decision.' },
          deliverable: { type: 'string', required: false, description: 'Published Markdown concept brief.' },
          rejection_reason: { type: 'string', required: false, description: 'Reason the workflow stopped.' },
        },
      },
      nodes: [
        { id: 'start', kind: 'trigger', label: 'Start', description: 'Accept a structured project intake.', reads: ['project_name', 'project_type', 'site_context', 'client_goals', 'constraints', 'evidence'], writes: [], config: {} },
        { id: 'normalize_brief', kind: 'function', label: 'Normalize brief', description: 'Create a stable project and design intent.', handler: 'architecture.normalize_brief', reads: ['project_name', 'project_type', 'site_context', 'client_goals', 'constraints'], writes: ['normalized_brief'], config: {} },
        { id: 'audit_evidence', kind: 'function', label: 'Audit evidence', description: 'Check source locators and surface unresolved evidence gaps.', handler: 'architecture.audit_evidence', reads: ['evidence', 'constraints'], writes: ['evidence_audit'], config: { evaluationId: 'evidence_coverage' } },
        { id: 'site_analysis', kind: 'agent', label: 'Site analysis', description: 'Translate site conditions and constraints into design impacts.', handler: 'architecture.site_analysis', reads: ['normalized_brief', 'site_context', 'constraints', 'evidence'], writes: ['site_findings'], config: { roleId: 'project_analyst' }, execution: { timeoutMs: 30_000, retry: { maxAttempts: 2, backoffMs: 100 } } },
        { id: 'program_analysis', kind: 'agent', label: 'Program analysis', description: 'Translate project goals into spatial and operational findings.', handler: 'architecture.program_analysis', reads: ['normalized_brief', 'client_goals', 'constraints', 'evidence'], writes: ['program_findings'], config: { roleId: 'project_analyst' }, execution: { timeoutMs: 30_000, retry: { maxAttempts: 2, backoffMs: 100 } } },
        { id: 'analysis_join', kind: 'join', label: 'Join analysis', description: 'Wait for site and program analysis.', reads: ['site_findings', 'program_findings'], writes: [], config: { mode: 'all' } },
        { id: 'develop_directions', kind: 'agent', label: 'Develop directions', description: 'Develop two distinct, constraint-aware concept directions.', handler: 'architecture.develop_directions', reads: ['normalized_brief', 'site_findings', 'program_findings', 'constraints'], writes: ['concept_directions'], config: { roleId: 'design_strategist' }, execution: { timeoutMs: 30_000, retry: { maxAttempts: 2, backoffMs: 100 } } },
        { id: 'evaluate_directions', kind: 'function', label: 'Evaluate directions', description: 'Compare directions against goals, evidence, feasibility, and distinction.', handler: 'architecture.evaluate_directions', reads: ['client_goals', 'constraints', 'evidence', 'concept_directions'], writes: ['option_evaluation'], config: { evaluationId: 'option_distinction' } },
        { id: 'quality_gate', kind: 'function', label: 'Quality gate', description: 'Block publication when evidence or option distinction is insufficient.', handler: 'architecture.quality_gate', reads: ['evidence_audit', 'concept_directions', 'option_evaluation'], writes: ['review_status'], config: { evaluationId: 'evidence_coverage' } },
        { id: 'approval', kind: 'human', label: 'Design review', description: 'Pause for a design reviewer to approve or reject the brief.', reads: ['normalized_brief', 'concept_directions', 'option_evaluation', 'review_status'], writes: ['approved'], config: { decisionField: 'approved', roleId: 'design_reviewer', evaluationId: 'human_approval' } },
        { id: 'approval_route', kind: 'router', label: 'Route review', description: 'Route approved and rejected work.', reads: ['approved'], writes: [], config: {} },
        { id: 'publish', kind: 'function', label: 'Publish concept brief', description: 'Assemble the approved project record into one traceable deliverable.', handler: 'architecture.publish', reads: ['project_name', 'project_type', 'site_context', 'client_goals', 'constraints', 'evidence', 'site_findings', 'program_findings', 'concept_directions', 'option_evaluation', 'review_status', 'approved'], writes: ['deliverable'], config: {} },
        { id: 'record_rejection', kind: 'function', label: 'Record rejection', description: 'Record why the concept brief was not published.', handler: 'architecture.record_rejection', reads: ['review_status', 'approved'], writes: ['rejection_reason'], config: {} },
      ],
      edges: [
        { id: 'e_start_normalize', source: 'start', target: 'normalize_brief', on: 'success' },
        { id: 'e_normalize_audit', source: 'normalize_brief', target: 'audit_evidence', on: 'success' },
        { id: 'e_audit_site', source: 'audit_evidence', target: 'site_analysis', on: 'success' },
        { id: 'e_audit_program', source: 'audit_evidence', target: 'program_analysis', on: 'success' },
        { id: 'e_site_join', source: 'site_analysis', target: 'analysis_join', on: 'success' },
        { id: 'e_program_join', source: 'program_analysis', target: 'analysis_join', on: 'success' },
        { id: 'e_join_directions', source: 'analysis_join', target: 'develop_directions', on: 'success' },
        { id: 'e_directions_evaluate', source: 'develop_directions', target: 'evaluate_directions', on: 'success' },
        { id: 'e_evaluate_quality', source: 'evaluate_directions', target: 'quality_gate', on: 'success' },
        { id: 'e_quality_approval', source: 'quality_gate', target: 'approval', on: 'success' },
        { id: 'e_approval_route', source: 'approval', target: 'approval_route', on: 'success' },
        { id: 'e_route_publish', source: 'approval_route', target: 'publish', on: 'success', condition: { field: 'approved', operator: 'equals', value: true }, label: 'Approved' },
        { id: 'e_route_reject', source: 'approval_route', target: 'record_rejection', on: 'success', condition: { field: 'approved', operator: 'equals', value: false }, label: 'Rejected' },
      ],
      budget: { maxSteps: 40, maxDurationMs: 120_000, maxConcurrency: 4 },
    },
  ],
};
