import type { IndustryPackManifest } from '@graph-workbench/contracts';

export const softwareDeliveryPack: IndustryPackManifest = {
  id: 'software_delivery',
  version: '0.5.0',
  name: 'Professional Software Delivery Pack',
  description:
    'A governed issue-to-release workflow with requirement traceability, risk classification, parallel verification, independent human gates, immutable release records, deployment observation, escalation and rollback.',
  license: 'MIT',
  ontology: {
    objectTypes: [
      {
        id: 'work_item',
        label: 'Work item',
        description: 'A delivery request with explicit acceptance criteria and assessed risk.',
        fields: {
          issue_id: { type: 'string', required: true, description: 'Stable work-item identifier.' },
          title: { type: 'string', required: true, description: 'User-facing outcome or problem.' },
          acceptance_criteria: { type: 'array', required: true, description: 'Testable acceptance criteria.' },
          risk_level: { type: 'string', required: true, description: 'Assessed delivery risk.' },
        },
      },
      {
        id: 'repository',
        label: 'Repository',
        description: 'The source-control boundary affected by a change.',
        fields: {
          name: { type: 'string', required: true, description: 'Repository locator.' },
          ref: { type: 'string', required: true, description: 'Protected base reference.' },
        },
      },
      {
        id: 'change_set',
        label: 'Change set',
        description: 'A reviewable and reversible proposed software change.',
        fields: {
          summary: { type: 'string', required: true, description: 'Change summary.' },
          affected_components: { type: 'array', required: true, description: 'Affected components.' },
          reversible: { type: 'boolean', required: true, description: 'Whether rollback is planned.' },
        },
      },
      {
        id: 'change_request',
        label: 'Change request',
        description: 'A pull or merge request carrying the proposed change through protected review.',
        fields: {
          change_request_id: { type: 'string', required: true, description: 'Stable change-request identifier.' },
          url: { type: 'string', required: true, description: 'Source-control review locator.' },
          status: { type: 'string', required: true, description: 'Review lifecycle status.' },
        },
      },
      {
        id: 'verification',
        label: 'Verification',
        description: 'A test, security or supply-chain check with attributable evidence.',
        fields: {
          check_id: { type: 'string', required: true, description: 'Stable check identifier.' },
          type: { type: 'string', required: true, description: 'Verification discipline.' },
          status: { type: 'string', required: true, description: 'Verification outcome.' },
          evidence_uri: { type: 'string', required: true, description: 'Immutable evidence locator.' },
        },
      },
      {
        id: 'review_decision',
        label: 'Review decision',
        description: 'An accountable human decision at a delivery gate.',
        fields: {
          gate: { type: 'string', required: true, description: 'Code-review or release gate.' },
          approved: { type: 'boolean', required: true, description: 'Decision outcome.' },
        },
      },
      {
        id: 'release',
        label: 'Release',
        description: 'An approved immutable release candidate or observed release reference.',
        fields: {
          release_id: { type: 'string', required: true, description: 'Stable release identifier.' },
          version: { type: 'string', required: true, description: 'Release version.' },
          environment: { type: 'string', required: true, description: 'Target environment.' },
          artifact_digest: { type: 'string', required: true, description: 'Immutable release artifact digest.' },
          status: { type: 'string', required: true, description: 'Readiness or observation status.' },
        },
      },
      {
        id: 'build_provenance',
        label: 'Build provenance',
        description: 'A reference to the builder, source and attestation that produced an artifact.',
        fields: {
          builder_id: { type: 'string', required: true, description: 'Build platform identity.' },
          build_type: { type: 'string', required: true, description: 'Build process type.' },
          source_ref: { type: 'string', required: true, description: 'Immutable source reference.' },
          artifact_digest: { type: 'string', required: true, description: 'Produced artifact digest.' },
          attestation_uri: { type: 'string', required: true, description: 'Attestation locator.' },
        },
      },
      {
        id: 'deployment_request',
        label: 'Deployment request',
        description: 'An approved request to promote an immutable release artifact.',
        fields: {
          request_id: { type: 'string', required: true, description: 'Stable promotion request.' },
          release_id: { type: 'string', required: true, description: 'Release being promoted.' },
          environment: { type: 'string', required: true, description: 'Promotion target.' },
          status: { type: 'string', required: true, description: 'Request status.' },
        },
      },
      {
        id: 'deployment',
        label: 'Deployment',
        description: 'An observed promotion of a release into an environment.',
        fields: {
          deployment_id: { type: 'string', required: true, description: 'Deployment identifier.' },
          release_id: { type: 'string', required: true, description: 'Promoted release identifier.' },
          environment: { type: 'string', required: true, description: 'Deployment environment.' },
          healthy: { type: 'boolean', required: true, description: 'Health-gate outcome.' },
        },
      },
      {
        id: 'incident',
        label: 'Delivery incident',
        description: 'An unhealthy deployment and its recovery outcome.',
        fields: {
          release_id: { type: 'string', required: true, description: 'Affected release.' },
          deployment_id: { type: 'string', required: true, description: 'Affected deployment.' },
          status: { type: 'string', required: true, description: 'Observed failure state.' },
          rollback_completed: { type: 'boolean', required: true, description: 'Whether rollback completed.' },
        },
      },
      {
        id: 'delivery_record',
        label: 'Delivery record',
        description: 'A portable human-readable release or operational record.',
        fields: {
          record_type: { type: 'string', required: true, description: 'Release or deployment record.' },
          content: { type: 'string', required: true, description: 'Markdown record content.' },
        },
      },
    ],
    relationTypes: [
      {
        id: 'targets',
        label: 'Targets',
        description: 'A work item targets a repository.',
        sourceTypes: ['work_item'],
        targetTypes: ['repository'],
      },
      {
        id: 'implements',
        label: 'Implements',
        description: 'A change set implements a work item.',
        sourceTypes: ['change_set'],
        targetTypes: ['work_item'],
      },
      {
        id: 'belongs_to',
        label: 'Belongs to',
        description: 'A change set belongs to a repository.',
        sourceTypes: ['change_set'],
        targetTypes: ['repository'],
      },
      {
        id: 'proposed_as',
        label: 'Proposed as',
        description: 'A change set is proposed through a protected change request.',
        sourceTypes: ['change_set'],
        targetTypes: ['change_request'],
      },
      {
        id: 'validates',
        label: 'Validates',
        description: 'Verification evidence validates a change set.',
        sourceTypes: ['verification'],
        targetTypes: ['change_set'],
      },
      {
        id: 'governs',
        label: 'Governs',
        description: 'A review decision governs a change or release.',
        sourceTypes: ['review_decision'],
        targetTypes: ['change_set', 'release'],
      },
      {
        id: 'contains_change',
        label: 'Contains change',
        description: 'A release contains an approved change set.',
        sourceTypes: ['release'],
        targetTypes: ['change_set'],
      },
      {
        id: 'produces',
        label: 'Produces',
        description: 'Build provenance identifies how a release artifact was produced.',
        sourceTypes: ['build_provenance'],
        targetTypes: ['release'],
      },
      {
        id: 'requests_promotion',
        label: 'Requests promotion',
        description: 'A deployment request promotes an approved release.',
        sourceTypes: ['deployment_request'],
        targetTypes: ['release'],
      },
      {
        id: 'promotes',
        label: 'Promotes',
        description: 'A deployment promotes a release.',
        sourceTypes: ['deployment'],
        targetTypes: ['release'],
      },
      {
        id: 'affects',
        label: 'Affects',
        description: 'A delivery incident affects a deployment.',
        sourceTypes: ['incident'],
        targetTypes: ['deployment'],
      },
      {
        id: 'documents',
        label: 'Documents',
        description: 'A delivery record documents a release, deployment or incident.',
        sourceTypes: ['delivery_record'],
        targetTypes: ['release', 'deployment', 'incident'],
      },
    ],
  },
  roles: [
    {
      id: 'delivery_lead',
      label: 'Delivery lead',
      mission: 'Keep requirements testable, scope bounded and delivery risk explicit.',
      allowedTools: ['work_item_read', 'repository_read'],
      forbiddenActions: ['Treating an untestable request as release-ready'],
    },
    {
      id: 'software_engineer',
      label: 'Software engineer',
      mission: 'Produce the smallest reversible change that satisfies the accepted requirement.',
      allowedTools: ['work_item_read', 'repository_read', 'change_request_upsert'],
      forbiddenActions: ['Bypassing protected-branch review', 'Hiding known verification failures'],
    },
    {
      id: 'quality_engineer',
      label: 'Quality engineer',
      mission: 'Verify functional behavior, regression safety and attributable test evidence.',
      allowedTools: ['work_item_read', 'repository_read'],
      forbiddenActions: ['Marking a check passed without an evidence locator'],
    },
    {
      id: 'security_reviewer',
      label: 'Security reviewer',
      mission: 'Assess code and software-supply-chain risk independently from implementation.',
      allowedTools: ['repository_read'],
      forbiddenActions: ['Suppressing an unresolved blocking finding'],
    },
    {
      id: 'code_owner',
      label: 'Code owner',
      mission: 'Approve requirement fit, maintainability and operational safety of the change.',
      allowedTools: ['work_item_read', 'repository_read'],
      forbiddenActions: ['Approving a change with a failed blocking quality gate'],
    },
    {
      id: 'release_manager',
      label: 'Release manager',
      mission: 'Authorize promotion only when evidence, rollback and ownership are complete.',
      allowedTools: ['repository_read', 'deployment_execute', 'deployment_rollback'],
      forbiddenActions: ['Deploying an unapproved release candidate'],
    },
    {
      id: 'service_owner',
      label: 'Service owner',
      mission: 'Own post-deployment health, incident escalation and restoration.',
      allowedTools: ['repository_read', 'deployment_rollback'],
      forbiddenActions: ['Leaving an unhealthy production deployment without an accountable response'],
    },
  ],
  tools: [
    {
      id: 'work_item_read',
      label: 'Read work item',
      risk: 'read',
      description: 'Read an issue or ticket without changing it.',
      operation: 'query',
      inputSchema: {
        type: 'object',
        properties: { issue_id: { type: 'string', minLength: 1 } },
        required: ['issue_id'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          issue_id: { type: 'string' },
          title: { type: 'string' },
          status: { type: 'string' },
        },
        required: ['issue_id', 'title', 'status'],
        additionalProperties: false,
      },
      idempotency: 'intrinsic',
    },
    {
      id: 'repository_read',
      label: 'Read repository',
      risk: 'read',
      description: 'Resolve a repository reference and immutable commit identifier.',
      operation: 'query',
      inputSchema: {
        type: 'object',
        properties: { repository: { type: 'string' }, ref: { type: 'string' } },
        required: ['repository', 'ref'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          repository: { type: 'string' },
          ref: { type: 'string' },
          commit_sha: { type: 'string' },
        },
        required: ['repository', 'ref', 'commit_sha'],
        additionalProperties: false,
      },
      idempotency: 'intrinsic',
    },
    {
      id: 'change_request_upsert',
      label: 'Create or update change request',
      risk: 'write',
      description: 'Create or update a pull or merge request with a stable idempotency key.',
      operation: 'command',
      inputSchema: {
        type: 'object',
        properties: {
          idempotency_key: { type: 'string' },
          repository: { type: 'string' },
          title: { type: 'string' },
          head: { type: 'string' },
          base: { type: 'string' },
        },
        required: ['idempotency_key', 'repository', 'title', 'head', 'base'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          change_request_id: { type: 'string' },
          url: { type: 'string' },
          status: { type: 'string' },
        },
        required: ['change_request_id', 'url', 'status'],
        additionalProperties: false,
      },
      idempotency: 'keyed',
      idempotencyKeyField: 'idempotency_key',
    },
    {
      id: 'deployment_execute',
      label: 'Execute deployment',
      risk: 'external',
      description: 'Request promotion of an approved immutable artifact.',
      operation: 'command',
      inputSchema: {
        type: 'object',
        properties: {
          idempotency_key: { type: 'string' },
          release_id: { type: 'string' },
          environment: { type: 'string' },
          artifact_digest: { type: 'string' },
        },
        required: ['idempotency_key', 'release_id', 'environment', 'artifact_digest'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { deployment_id: { type: 'string' }, status: { type: 'string' } },
        required: ['deployment_id', 'status'],
        additionalProperties: false,
      },
      idempotency: 'keyed',
      idempotencyKeyField: 'idempotency_key',
    },
    {
      id: 'deployment_rollback',
      label: 'Rollback deployment',
      risk: 'external',
      description: 'Request rollback of an unhealthy deployment.',
      operation: 'command',
      inputSchema: {
        type: 'object',
        properties: {
          idempotency_key: { type: 'string' },
          deployment_id: { type: 'string' },
        },
        required: ['idempotency_key', 'deployment_id'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { rollback_id: { type: 'string' }, status: { type: 'string' } },
        required: ['rollback_id', 'status'],
        additionalProperties: false,
      },
      idempotency: 'keyed',
      idempotencyKeyField: 'idempotency_key',
    },
  ],
  evaluations: [
    {
      id: 'requirement_traceability',
      label: 'Requirement traceability',
      description: 'The work item has explicit acceptance criteria linked to a bounded change.',
      blocking: true,
    },
    {
      id: 'release_verification',
      label: 'Release verification',
      description: 'Unit, integration, security and supply-chain checks all pass with evidence.',
      blocking: true,
    },
    {
      id: 'code_owner_approval',
      label: 'Code-owner approval',
      description: 'An accountable code owner approves the verified change.',
      blocking: true,
    },
    {
      id: 'release_approval',
      label: 'Release approval',
      description: 'A release manager approves promotion and rollback readiness.',
      blocking: true,
    },
    {
      id: 'deployment_health',
      label: 'Deployment health',
      description: 'Post-deployment signals confirm health or trigger escalation and rollback.',
      blocking: true,
    },
  ],
  deliverables: [
    {
      id: 'release_readiness_record',
      label: 'Release readiness record',
      description: 'A reviewed Markdown record linking requirement, change, evidence and approvals.',
      graphId: 'software_delivery.change_to_release',
      stateField: 'release_record',
      mediaType: 'text/markdown',
      artifactType: 'release_readiness_record',
      evidenceFields: ['risk_assessment', 'verification_results', 'quality_summary', 'build_provenance'],
      approvalField: 'release_approved',
    },
    {
      id: 'deployment_observation_record',
      label: 'Deployment observation record',
      description: 'A health or incident record with post-deployment evidence and recovery outcome.',
      graphId: 'software_delivery.observe_deployment',
      stateField: 'deployment_record',
      mediaType: 'text/markdown',
      artifactType: 'deployment_observation_record',
      evidenceFields: ['health_signals', 'observation_summary'],
    },
  ],
  fixtures: [
    {
      id: 'standard_feature_release',
      label: 'Standard feature release',
      description: 'A normal production feature passes traceability, verification and two human gates.',
      graphId: 'software_delivery.change_to_release',
      input: {
        issue_id: 'PLAT-142',
        title: 'Add idempotent invoice export',
        repository: 'acme/billing-api',
        base_ref: 'main',
        target_environment: 'production',
        release_version: '2.8.0',
        artifact_digest: 'sha256:1111111111111111111111111111111111111111111111111111111111111111',
        acceptance_criteria: [
          'Repeated export requests with the same key return one export.',
          'Exports include an auditable source invoice identifier.',
          'Existing invoice retrieval latency remains within the service objective.',
        ],
        affected_components: ['invoice-export', 'api-contract', 'observability'],
        risk_flags: ['customer-data', 'public-api'],
      },
      decisions: { code_review: true, release_approval: true },
      expectations: [
        { field: 'verification_results', operator: 'min_items', value: 4, description: 'Runs all required verification disciplines.' },
        { field: 'quality_summary', operator: 'exists', description: 'Produces a blocking quality summary.' },
        { field: 'release_record', operator: 'includes', value: '# Release readiness record', description: 'Publishes the approved release record.' },
      ],
    },
    {
      id: 'critical_hotfix',
      label: 'Critical hotfix',
      description: 'A high-risk production fix keeps the same evidence and approval standard.',
      graphId: 'software_delivery.change_to_release',
      input: {
        issue_id: 'INC-907',
        title: 'Stop duplicate payment capture retries',
        repository: 'acme/payments',
        base_ref: 'main',
        target_environment: 'production',
        release_version: '4.12.3',
        artifact_digest: 'sha256:2222222222222222222222222222222222222222222222222222222222222222',
        acceptance_criteria: [
          'A payment intent is captured at most once.',
          'Retry processing preserves existing reconciliation identifiers.',
          'Rollback restores the previous worker without data migration.',
        ],
        affected_components: ['capture-worker', 'idempotency-store'],
        risk_flags: ['payments', 'customer-data', 'incident-hotfix'],
      },
      decisions: { code_review: true, release_approval: true },
      expectations: [
        { field: 'risk_assessment', operator: 'exists', description: 'Makes hotfix risk explicit.' },
        { field: 'release_record', operator: 'includes', value: 'critical', description: 'Carries critical risk into the release record.' },
      ],
    },
    {
      id: 'healthy_deployment',
      label: 'Healthy deployment observation',
      description: 'A deployment event is confirmed healthy from multiple service signals.',
      graphId: 'software_delivery.observe_deployment',
      input: {
        release_id: 'acme/billing-api@2.8.0',
        deployment_id: 'deploy-481',
        environment: 'production',
        status: 'succeeded',
        artifact_digest: 'sha256:1111111111111111111111111111111111111111111111111111111111111111',
        health_signals: [
          { name: 'error_rate', status: 'healthy', value: 0.001 },
          { name: 'latency_slo', status: 'healthy', value: 0.99 },
        ],
      },
      decisions: {},
      expectations: [
        { field: 'deployment_healthy', operator: 'equals', value: true, description: 'Confirms deployment health.' },
        { field: 'deployment_record', operator: 'includes', value: 'Outcome: healthy', description: 'Publishes a healthy observation record.' },
      ],
    },
    {
      id: 'failed_deployment_rollback',
      label: 'Failed deployment rollback',
      description: 'An unhealthy deployment raises an escalation and records explicit compensation.',
      graphId: 'software_delivery.observe_deployment',
      input: {
        release_id: 'acme/payments@4.12.3',
        deployment_id: 'deploy-907',
        environment: 'production',
        status: 'failed',
        artifact_digest: 'sha256:2222222222222222222222222222222222222222222222222222222222222222',
        health_signals: [
          { name: 'payment_error_rate', status: 'failed', value: 0.12 },
          { name: 'reconciliation_lag', status: 'failed', value: 900 },
        ],
      },
      decisions: {},
      expectations: [
        { field: 'rollback_completed', operator: 'equals', value: true, description: 'Completes the declared rollback compensation.' },
        { field: 'deployment_record', operator: 'includes', value: 'Rollback: completed', description: 'Publishes recovery evidence.' },
      ],
    },
  ],
  graphs: [
    {
      id: 'software_delivery.change_to_release',
      version: 1,
      name: 'Issue-to-release governance',
      description: 'Normalize a work item, assess risk, plan a reversible change, execute parallel verification and require independent code-owner and release-manager approval.',
      // A delivery request can only be governed once its artifact exists, so the
      // ingress is the build that produced the digest — not the issue that
      // requested the change. A CI job posts this after a successful build.
      trigger: {
        type: 'webhook',
        method: 'POST',
        path: '/software-delivery/delivery-request',
        inputSchema: {
          type: 'object',
          properties: {
            issue_id: { type: 'string', minLength: 1 },
            title: { type: 'string', minLength: 1 },
            repository: { type: 'string', minLength: 1 },
            base_ref: { type: 'string', minLength: 1 },
            target_environment: { type: 'string', minLength: 1 },
            release_version: { type: 'string', minLength: 1 },
            artifact_digest: { type: 'string', minLength: 1 },
            acceptance_criteria: { type: 'array', items: { type: 'string' } },
            affected_components: { type: 'array', items: { type: 'string' } },
            risk_flags: { type: 'array', items: { type: 'string' } },
          },
          required: [
            'issue_id', 'title', 'repository', 'base_ref', 'target_environment',
            'release_version', 'artifact_digest', 'acceptance_criteria',
            'affected_components', 'risk_flags',
          ],
          additionalProperties: false,
        },
      },
      state: {
        fields: {
          issue_id: { type: 'string', required: true, description: 'Stable issue identifier.' },
          title: { type: 'string', required: true, description: 'Requested outcome.' },
          repository: { type: 'string', required: true, description: 'Repository locator.' },
          base_ref: { type: 'string', required: true, description: 'Protected base reference.' },
          target_environment: { type: 'string', required: true, description: 'Promotion target.' },
          release_version: { type: 'string', required: true, description: 'Requested release version.' },
          artifact_digest: { type: 'string', required: true, description: 'Immutable artifact digest from the build platform.' },
          acceptance_criteria: { type: 'array', required: true, description: 'Testable acceptance criteria.' },
          affected_components: { type: 'array', required: true, description: 'Affected components.' },
          risk_flags: { type: 'array', required: true, description: 'Known delivery-risk flags.' },
          intake: { type: 'object', required: false, description: 'Normalized work intake.' },
          risk_assessment: { type: 'object', required: false, description: 'Delivery risk score and rationale.' },
          delivery_plan: { type: 'array', required: false, description: 'Bounded delivery plan.' },
          change_set: { type: 'object', required: false, description: 'Reviewable change summary.' },
          change_request: { type: 'object', required: false, description: 'Protected source-control review request.' },
          check_requests: { type: 'array', required: false, description: 'Required verification work.' },
          verification_results: { type: 'array', required: false, description: 'Attributable check results.' },
          quality_summary: { type: 'object', required: false, description: 'Blocking quality result.' },
          code_review_approved: { type: 'boolean', required: false, description: 'Code-owner decision.' },
          merge_record: { type: 'object', required: false, description: 'Approved merge result.' },
          release_candidate: { type: 'object', required: false, description: 'Immutable promotion candidate.' },
          build_provenance: { type: 'object', required: false, description: 'Builder, source and attestation reference.' },
          release_approved: { type: 'boolean', required: false, description: 'Release-manager decision.' },
          deployment_request: { type: 'object', required: false, description: 'Approved promotion request.' },
          release_record: { type: 'string', required: false, description: 'Approved release readiness record.' },
          rejection_reason: { type: 'string', required: false, description: 'Reason delivery stopped.' },
        },
      },
      nodes: [
        { id: 'start', kind: 'trigger', label: 'Issue intake', description: 'Accept a structured delivery request.', reads: ['issue_id', 'title', 'repository', 'base_ref', 'target_environment', 'release_version', 'artifact_digest', 'acceptance_criteria', 'affected_components', 'risk_flags'], writes: [], config: {} },
        { id: 'normalize_intake', kind: 'function', label: 'Normalize intake', description: 'Create a stable work-item boundary.', handler: 'software_delivery.normalize_intake', reads: ['issue_id', 'title', 'repository', 'acceptance_criteria', 'target_environment'], writes: ['intake'], config: { roleId: 'delivery_lead', evaluationId: 'requirement_traceability' } },
        { id: 'assess_risk', kind: 'function', label: 'Assess delivery risk', description: 'Classify change and production risk before implementation.', handler: 'software_delivery.assess_risk', reads: ['risk_flags', 'target_environment'], writes: ['risk_assessment'], config: { roleId: 'delivery_lead' } },
        { id: 'plan_change', kind: 'agent', label: 'Plan reversible change', description: 'Plan the smallest reversible implementation and evidence set.', handler: 'software_delivery.plan_change', reads: ['issue_id', 'repository', 'target_environment', 'intake', 'risk_assessment'], writes: ['delivery_plan'], config: { roleId: 'software_engineer', toolIds: ['work_item_read', 'repository_read'] } },
        { id: 'build_change_set', kind: 'agent', label: 'Build change set', description: 'Describe the bounded implementation that a source-control adapter will carry.', handler: 'software_delivery.build_change_set', reads: ['issue_id', 'title', 'repository', 'base_ref', 'affected_components', 'delivery_plan'], writes: ['change_set'], config: { roleId: 'software_engineer', toolIds: ['repository_read', 'change_request_upsert'] } },
        { id: 'open_change_request', kind: 'function', label: 'Open change request', description: 'Make the protected source-control review boundary explicit.', handler: 'software_delivery.open_change_request', reads: ['issue_id', 'repository', 'base_ref', 'change_set'], writes: ['change_request'], config: { roleId: 'software_engineer' } },
        { id: 'prepare_checks', kind: 'function', label: 'Prepare verification', description: 'Declare the required functional, security and supply-chain checks.', handler: 'software_delivery.prepare_checks', reads: ['risk_assessment', 'change_set'], writes: ['check_requests'], config: {} },
        { id: 'run_checks', kind: 'map', label: 'Run verification', description: 'Execute independent checks with bounded concurrency.', reads: ['check_requests', 'repository', 'change_set'], writes: ['verification_results'], config: { graphId: 'software_delivery.run_check', itemsField: 'check_requests', itemField: 'check', resultField: 'result', outputField: 'verification_results', inputMapping: { repository: 'repository', change_set: 'change_set' }, maxItems: 8, maxConcurrency: 4 } },
        { id: 'quality_gate', kind: 'function', label: 'Release quality gate', description: 'Require all release disciplines and evidence before human review.', handler: 'software_delivery.quality_gate', reads: ['verification_results', 'risk_assessment'], writes: ['quality_summary'], config: { evaluationId: 'release_verification' } },
        { id: 'quality_failure', kind: 'escalation', label: 'Escalate quality failure', description: 'Make a failed blocking gate visible to the delivery lead.', reads: ['issue_id'], writes: [], config: { reason: 'Release verification failed before code-owner review.', severity: 'high', roleId: 'delivery_lead' } },
        { id: 'record_quality_failure', kind: 'function', label: 'Record quality failure', description: 'Stop release preparation and preserve the failed gate.', handler: 'software_delivery.record_quality_failure', reads: ['issue_id'], writes: ['rejection_reason'], config: {} },
        { id: 'code_review', kind: 'human', label: 'Code-owner review', description: 'Approve requirement fit, maintainability and operational safety.', reads: ['intake', 'risk_assessment', 'change_set', 'verification_results', 'quality_summary'], writes: ['code_review_approved'], config: { decisionField: 'code_review_approved', roleId: 'code_owner', evaluationId: 'code_owner_approval' } },
        { id: 'code_review_route', kind: 'router', label: 'Route code review', description: 'Continue only when the code owner approves.', reads: ['code_review_approved'], writes: [], config: {} },
        { id: 'merge_change', kind: 'function', label: 'Merge approved change', description: 'Record the protected merge after code-owner approval.', handler: 'software_delivery.merge_change', reads: ['repository', 'release_version', 'change_request', 'change_set', 'code_review_approved'], writes: ['merge_record'], config: { roleId: 'software_engineer' } },
        { id: 'prepare_release', kind: 'function', label: 'Prepare release candidate', description: 'Bind source, immutable artifact, provenance and verification into one candidate.', handler: 'software_delivery.prepare_release', reads: ['repository', 'release_version', 'artifact_digest', 'target_environment', 'change_set', 'merge_record', 'verification_results'], writes: ['release_candidate', 'build_provenance'], config: {} },
        { id: 'release_approval', kind: 'human', label: 'Release approval', description: 'Authorize promotion with independent release accountability.', reads: ['issue_id', 'risk_assessment', 'quality_summary', 'release_candidate'], writes: ['release_approved'], config: { decisionField: 'release_approved', roleId: 'release_manager', evaluationId: 'release_approval' } },
        { id: 'release_route', kind: 'router', label: 'Route release decision', description: 'Publish only approved release candidates.', reads: ['release_approved'], writes: [], config: {} },
        { id: 'request_deployment', kind: 'function', label: 'Request deployment', description: 'Request promotion of the approved immutable artifact.', handler: 'software_delivery.request_deployment', reads: ['issue_id', 'release_version', 'target_environment', 'release_candidate', 'release_approved'], writes: ['deployment_request'], config: { roleId: 'release_manager', toolIds: ['deployment_execute'] } },
        { id: 'publish_release', kind: 'function', label: 'Publish release record', description: 'Publish one traceable requirement-to-release record.', handler: 'software_delivery.publish_release', reads: ['issue_id', 'title', 'repository', 'target_environment', 'acceptance_criteria', 'risk_assessment', 'verification_results', 'change_request', 'release_candidate', 'build_provenance', 'deployment_request', 'code_review_approved', 'release_approved'], writes: ['release_record'], config: {} },
        { id: 'record_rejection', kind: 'function', label: 'Record rejection', description: 'Preserve the human decision that stopped delivery.', handler: 'software_delivery.record_rejection', reads: ['code_review_approved', 'release_approved'], writes: ['rejection_reason'], config: {} },
      ],
      edges: [
        { id: 'e_start_normalize', source: 'start', target: 'normalize_intake', on: 'success' },
        { id: 'e_normalize_risk', source: 'normalize_intake', target: 'assess_risk', on: 'success' },
        { id: 'e_risk_plan', source: 'assess_risk', target: 'plan_change', on: 'success' },
        { id: 'e_plan_change', source: 'plan_change', target: 'build_change_set', on: 'success' },
        { id: 'e_change_request', source: 'build_change_set', target: 'open_change_request', on: 'success' },
        { id: 'e_request_checks', source: 'open_change_request', target: 'prepare_checks', on: 'success' },
        { id: 'e_prepare_run', source: 'prepare_checks', target: 'run_checks', on: 'success' },
        { id: 'e_checks_quality', source: 'run_checks', target: 'quality_gate', on: 'success' },
        { id: 'e_quality_review', source: 'quality_gate', target: 'code_review', on: 'success' },
        { id: 'e_quality_escalate', source: 'quality_gate', target: 'quality_failure', on: 'failure' },
        { id: 'e_quality_record', source: 'quality_failure', target: 'record_quality_failure', on: 'success' },
        { id: 'e_review_route', source: 'code_review', target: 'code_review_route', on: 'success' },
        { id: 'e_review_merge', source: 'code_review_route', target: 'merge_change', on: 'success', condition: { field: 'code_review_approved', operator: 'equals', value: true }, label: 'Approved' },
        { id: 'e_review_reject', source: 'code_review_route', target: 'record_rejection', on: 'success', condition: { field: 'code_review_approved', operator: 'equals', value: false }, label: 'Rejected' },
        { id: 'e_merge_release', source: 'merge_change', target: 'prepare_release', on: 'success' },
        { id: 'e_prepare_approval', source: 'prepare_release', target: 'release_approval', on: 'success' },
        { id: 'e_approval_route', source: 'release_approval', target: 'release_route', on: 'success' },
        { id: 'e_release_deploy', source: 'release_route', target: 'request_deployment', on: 'success', condition: { field: 'release_approved', operator: 'equals', value: true }, label: 'Approved' },
        { id: 'e_release_reject', source: 'release_route', target: 'record_rejection', on: 'success', condition: { field: 'release_approved', operator: 'equals', value: false }, label: 'Rejected' },
        { id: 'e_deploy_publish', source: 'request_deployment', target: 'publish_release', on: 'success' },
      ],
      budget: { maxSteps: 64, maxDurationMs: 120_000, maxConcurrency: 4 },
    },
    {
      id: 'software_delivery.run_check',
      version: 1,
      name: 'Execute delivery check',
      description: 'A reusable child graph that turns one declared check into attributable verification evidence.',
      state: {
        fields: {
          check: { type: 'object', required: true, description: 'Check request.' },
          repository: { type: 'string', required: true, description: 'Repository locator.' },
          change_set: { type: 'object', required: true, description: 'Change under verification.' },
          result: { type: 'object', required: false, description: 'Verification result.' },
        },
      },
      nodes: [
        { id: 'start', kind: 'trigger', label: 'Check request', description: 'Accept one verification item.', reads: ['check', 'repository', 'change_set'], writes: [], config: {} },
        { id: 'execute_check', kind: 'function', label: 'Execute check', description: 'Produce a deterministic reference check result.', handler: 'software_delivery.execute_check', reads: ['check', 'repository', 'change_set'], writes: ['result'], config: { roleId: 'quality_engineer' } },
      ],
      edges: [{ id: 'e_start_execute', source: 'start', target: 'execute_check', on: 'success' }],
      budget: { maxSteps: 8, maxDurationMs: 30_000, maxConcurrency: 1 },
    },
    {
      id: 'software_delivery.observe_deployment',
      version: 1,
      name: 'Deployment health and recovery',
      description: 'Accept a typed deployment observation, publish healthy evidence or visibly escalate and compensate an unhealthy release.',
      trigger: {
        type: 'event',
        eventType: 'deployment.observed',
        correlationField: 'release_id',
        inputSchema: {
          type: 'object',
          properties: {
            deployment_id: { type: 'string' },
            environment: { type: 'string' },
            status: { type: 'string' },
            artifact_digest: { type: 'string' },
            health_signals: { type: 'array', items: { type: 'object' } },
          },
          required: ['deployment_id', 'environment', 'status', 'artifact_digest', 'health_signals'],
          additionalProperties: false,
        },
      },
      state: {
        fields: {
          release_id: { type: 'string', required: true, description: 'Observed release identifier.' },
          deployment_id: { type: 'string', required: true, description: 'Deployment identifier.' },
          environment: { type: 'string', required: true, description: 'Deployment environment.' },
          status: { type: 'string', required: true, description: 'Deployment status.' },
          artifact_digest: { type: 'string', required: true, description: 'Observed immutable artifact digest.' },
          health_signals: { type: 'array', required: true, description: 'Post-deployment health evidence.' },
          deployment_healthy: { type: 'boolean', required: false, description: 'Health-gate result.' },
          release_context: { type: 'object', required: false, description: 'Approved release context reused from a prior run.' },
          observation_summary: { type: 'object', required: false, description: 'Normalized deployment observation.' },
          rollback_completed: { type: 'boolean', required: false, description: 'Rollback compensation outcome.' },
          rollback_reference: { type: 'string', required: false, description: 'Rollback evidence locator.' },
          deployment_record: { type: 'string', required: false, description: 'Health or incident record.' },
        },
      },
      nodes: [
        { id: 'start', kind: 'trigger', label: 'Deployment observed', description: 'Accept a correlated deployment event.', reads: ['release_id', 'deployment_id', 'environment', 'status', 'artifact_digest', 'health_signals'], writes: [], config: {} },
        { id: 'assess_deployment', kind: 'function', label: 'Assess deployment', description: 'Evaluate deployment status and service health signals against approved release context.', handler: 'software_delivery.assess_deployment', reads: ['release_id', 'deployment_id', 'environment', 'status', 'health_signals'], writes: ['deployment_healthy', 'release_context', 'observation_summary'], config: { evaluationId: 'deployment_health' } },
        { id: 'health_route', kind: 'router', label: 'Route health', description: 'Separate healthy delivery from incident recovery.', reads: ['deployment_healthy'], writes: [], config: {} },
        { id: 'publish_healthy', kind: 'function', label: 'Publish healthy observation', description: 'Record successful production observation and the approved release context it reused.', handler: 'software_delivery.publish_healthy_observation', reads: ['release_id', 'deployment_id', 'environment', 'artifact_digest', 'health_signals', 'release_context', 'observation_summary'], writes: ['deployment_record'], config: {} },
        { id: 'escalate_incident', kind: 'escalation', label: 'Escalate deployment incident', description: 'Raise accountable incident response for an unhealthy deployment.', reads: ['release_id', 'deployment_id', 'observation_summary'], writes: [], config: { reason: 'Deployment health gate failed; service-owner response is required.', severity: 'critical', roleId: 'service_owner' } },
        { id: 'rollback', kind: 'compensation', label: 'Rollback deployment', description: 'Restore the last known good deployment.', handler: 'software_delivery.rollback_deployment', reads: ['release_id', 'deployment_id'], writes: ['rollback_completed', 'rollback_reference'], config: { compensates: ['assess_deployment'] } },
        { id: 'recovery_join', kind: 'join', label: 'Join recovery', description: 'Wait for escalation and rollback evidence.', reads: ['rollback_completed', 'rollback_reference'], writes: [], config: { mode: 'all' } },
        { id: 'publish_failed', kind: 'function', label: 'Publish incident record', description: 'Record unhealthy delivery, reused release context and compensation outcome.', handler: 'software_delivery.publish_failed_observation', reads: ['release_id', 'deployment_id', 'environment', 'status', 'artifact_digest', 'health_signals', 'release_context', 'observation_summary', 'rollback_completed', 'rollback_reference'], writes: ['deployment_record'], config: {} },
      ],
      edges: [
        { id: 'e_start_assess', source: 'start', target: 'assess_deployment', on: 'success' },
        { id: 'e_assess_route', source: 'assess_deployment', target: 'health_route', on: 'success' },
        { id: 'e_route_healthy', source: 'health_route', target: 'publish_healthy', on: 'success', condition: { field: 'deployment_healthy', operator: 'equals', value: true }, label: 'Healthy' },
        { id: 'e_route_escalate', source: 'health_route', target: 'escalate_incident', on: 'success', condition: { field: 'deployment_healthy', operator: 'equals', value: false }, label: 'Unhealthy' },
        { id: 'e_route_rollback', source: 'health_route', target: 'rollback', on: 'success', condition: { field: 'deployment_healthy', operator: 'equals', value: false }, label: 'Unhealthy' },
        { id: 'e_escalate_join', source: 'escalate_incident', target: 'recovery_join', on: 'success' },
        { id: 'e_rollback_join', source: 'rollback', target: 'recovery_join', on: 'success' },
        { id: 'e_join_publish', source: 'recovery_join', target: 'publish_failed', on: 'success' },
      ],
      budget: { maxSteps: 24, maxDurationMs: 60_000, maxConcurrency: 2 },
    },
  ],
};
